dart/collision/fcl_mesh/FCLMeshCollisionNode.cpp
Fix bug: Only the first collision shape of a body node is considered when checking for collision without calculating contact points
The change is smaller than it seems here. When ignoring whitespace changes, only 3 lines are changed.
I have only tested this bug fix with DART 3, but it should be the same for DART 4.
=> Fix bug in collision checking when a body node has multiple collision shapes

dart/dynamics/EulerJoint.cpp, dart/dynamics/EulerJoint.h
=> [Fix #321] Remove unsupported axis orders of EulerJoint

dart/dynamics/BallJoint.cpp, dart/dynamics/BallJoint.h, dart/dynamics/EulerJoint.cpp, dart/dynamics/EulerJoint.h, dart/dynamics/FreeJoint.cpp, dart/dynamics/FreeJoint.h, unittests/testJoints.cpp
I found that setting FreeJoint and other joint types that have rotations can be confusing or can require more lines of code than it ought to, so I made some functions to help users convert transform and rotation types into joint position vectors that they can pass into Joint::setPositions(VectorXd).
=> Added convenience functions to help with setting FreeJoint, EulerJoint, and BallJoint positions

dart/simulation/World.cpp, unittests/testWorld.cpp
This fix addresses two issues:
1) Skeleton names were not getting removed from the name manager in the World when those Skeletons were removed.
2) Skeletons were not being reassigned names when a Skeleton with a repeated name was added to the World
This fixes have been made and a regression test was created to ensure that these issues are fixed and remain fixed.
=> Fixed naming issues for Skeletons in World and created regression tests

dart/dynamics/FreeJoint.cpp, unittests/testJoints.cpp
This is a replacement for Pull Request #334, the difference being that this one does not use Eigen::AngleAxisd for exponential maps.
=> Fix the initialization for FreeJoint::convertToTransform()

dart/dynamics/SoftBodyNode.cpp, dart/utils/sdf/SoftSdfParser.cpp
The atlasSimbicon app is failing in master because of a segfault in the SoftSdfParser. It tries to call "getTransform()" on a BodyNode that does not yet have a parent joint, and this is guaranteed to result in a segfault, because the parent joint is strictly responsible for the relative transform of its child BodyNode. The parser has been corrected to set the transform-from-parent of the FreeJoint according to the initial transform as read by the SdfParser. However, we might want to consider setting that transform to Identity and using the initial transform to set the initial joint values of the FreeJoint. Either way works, but one might be semantically preferable over the other.
I also modified the warning message for the soft boxes to be a bit more clear.
=> Fixing segfault in SoftSdfParser

dart/dynamics/BodyNode.cpp, dart/dynamics/LineSegmentShape.cpp, dart/dynamics/LineSegmentShape.h, dart/dynamics/Shape.h, dart/math/Geometry.cpp, dart/math/Geometry.h, dart/math/Helpers.h, dart/renderer/OpenGLRenderInterface.cpp, dart/renderer/OpenGLRenderInterface.h, dart/renderer/RenderInterface.cpp, dart/renderer/RenderInterface.h
Line segments can now be added as visualization shapes for Entities (but not as collision shapes for BodyNodes). Collision checking with LineSegmentShape has **not** been implemented yet.
=> Implemented LineSegmentShape for visualizing line segments

dart/dynamics/Skeleton.cpp, dart/dynamics/Skeleton.h, unittests/testDynamics.cpp
`BodyNode::getJacobian()` returns (6 x m) matrix where m is the number of dependent dofs of the BodyNode while `Skeleton::getJacobian()` returns (6 x n) matrix where n is the number of total dofs of the Skeleton.
=> Add Jacobian getters to Skeleton

apps/simpleFrames/Main.cpp, dart/dynamics/ArrowShape.cpp, dart/dynamics/ArrowShape.h, dart/dynamics/MeshShape.cpp, dart/dynamics/MeshShape.h, dart/dynamics/Shape.h
I've created an ArrowShape which is just a specialization of the MeshShape.
This pull request also has constructors and destructors for aiScene, which allows us to delete aiScenes in the destructor of the MeshShape class. The only catch is that there is a ``void* mPrivate`` in the aiScene structure which cannot be properly destructed without some hidden internal assimp data structures. It's probably worth raising an issue with the assimp retainers to understand why certain important constructors and destructors are not included in their basic library.
=> Implemented ArrowShape for visualizing arrows

apps/simpleFrames/Main.cpp, apps/softBodies/Main.cpp, dart/dynamics/ArrowShape.cpp, dart/dynamics/ArrowShape.h, dart/dynamics/Shape.cpp, dart/dynamics/Shape.h, dart/math/Helpers.h
I've added an alpha channel for Shape colors. It turns out the whole OpenGL renderer pipeline was completely ready for an alpha channel, it just wasn't being used.
I also added some Color generating functions. Rather than create a Color class, I simply made a namespace called Color in dart/math/Helpers.h and put some functions in that namespace. I decided to inline all the functions so that end users can just check the header to see what actual color codes are being used for each of the color functions.
=> Added alpha channel and Color functions

dart/dynamics/MeshShape.cpp, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/DartLoader.h, dart/utils/urdf/urdf_world_parser.cpp
I made changes to the URDF parser so that it can handle package names and directories correctly (thanks @ehuang3 for the info), and while I was at it, I found that the parser was rife with poor error handling (including memory leaks and poorly explained exits) and screwy formatting, so I fixed some of that as well.
Now the URDF parsing can handle arbitrarily many different packages (instead of assuming that all resources will be in the same package), but it still depends on the user to specify the paths to the package directories.
I also added the ability to parse raw xml strings instead of only allowing xml files.
Note that there was a necessary API change in order to support multiple packages. This will not affect any users who were not using URDFs with ROS packages in the first place.
=> Better robustness and package handling for URDF parsing

dart/dynamics/PlaneShape.cpp, dart/dynamics/PlaneShape.h
Revert deprecation of PlaneShape constructor that takes normal and point parameters based on the discussion in #373. Also add setNormalAndOffset and setNormalAndPoint.
=> Reverting PlaneShape constructor taking normal and point parameters

dart/dynamics/SimpleFrame.cpp, dart/dynamics/SimpleFrame.h, unittests/testFrames.cpp
This pull request adds a new function to the API that allows the user to set the transform of a SimpleFrame such that it has a specified transform with respect to some other Frame. The parent Frame of the SimpleFrame remains unchanged.
=> New setTransform function for SimpleFrame

dart/common/Deprecated.h
=> Add deprecated and force-inline definitions for clang

dart/dynamics/Skeleton.cpp
This pull request fixes a bug in the range check in `Skeleton::getRootBodyNode`. The condition was inverted, which made it impossible to call this function.
=> Fixed the range check in getRootBodyNode.

dart/dynamics/BallJoint.h, dart/dynamics/EulerJoint.h, dart/dynamics/FreeJoint.h, dart/dynamics/Joint.h, dart/dynamics/MultiDofJoint.h, dart/dynamics/PlanarJoint.h, dart/dynamics/PrismaticJoint.h, dart/dynamics/RevoluteJoint.h, dart/dynamics/ScrewJoint.h, dart/dynamics/SingleDofJoint.h, dart/dynamics/TranslationalJoint.h, dart/dynamics/UniversalJoint.h, dart/dynamics/WeldJoint.h, dart/dynamics/ZeroDofJoint.h
This pull request adds default virtual constructors to all joint `Properties` classes. These classes are polymorphic, so this is generally a good idea from a safety perspective. This is also necessary for RTTI to work on these classes (which we need to create Python bindings).
=> Added virtual destructors to joint properties.

dart/dynamics/BallJoint.cpp, dart/dynamics/BallJoint.h, dart/dynamics/EulerJoint.cpp, dart/dynamics/EulerJoint.h, dart/dynamics/FreeJoint.cpp, dart/dynamics/FreeJoint.h, dart/dynamics/Joint.h, dart/dynamics/MultiDofJoint.h, dart/dynamics/PlanarJoint.cpp, dart/dynamics/PlanarJoint.h, dart/dynamics/SingleDofJoint.cpp, dart/dynamics/SingleDofJoint.h, dart/dynamics/Skeleton.cpp, dart/dynamics/Skeleton.h, dart/dynamics/TranslationalJoint.cpp, dart/dynamics/TranslationalJoint.h, dart/dynamics/UniversalJoint.cpp, dart/dynamics/UniversalJoint.h, dart/dynamics/ZeroDofJoint.cpp, dart/dynamics/ZeroDofJoint.h, unittests/testDynamics.cpp
This pull request provides useful API for computing generalized velocity or acceleration using finite difference method. Previously, the finite differences for BallJoint and FreeJoint required special treatment that might not be straightforward.
Example code (when the root Joint is FreeJoint or BallJoint):
```cpp
// time step and recorded generalized positions
double h = mWorld->getTimeStep();
Eigen::VectorXd q0 = mWorld->getRecording()->getConfig(49, 0);
Eigen::VectorXd q1 = mWorld->getRecording()->getConfig(50, 0);
Eigen::VectorXd q2 = mWorld->getRecording()->getConfig(51, 0);
// Old API
Eigen::VectorXd q_old = skeleton->getPositions();
skeleton->setPositions(q0);
Eigen::MatrixXd Jw0 = skeleton->getJoint(0)->getLocalJacobian().topLeftCorner<3,3>();
Eigen::VectorXd dq0 = (q1 - q0) / h; …
```
=> Differences of generalized coordinates

dart/dynamics/MeshShape.cpp, dart/dynamics/MeshShape.h, dart/utils/urdf/DartLoader.cpp
This pull request adds a `getMeshPath` method to `MeshShape`. This returns the path to mesh on disk if it is available. If not, it returns an empty string (the default behavior).
This information is necessary to render meshes with non-embedded textures. Assimp references external textures with a path relative to the directory containing the mesh.
=> Store path to mesh in MeshShape

dart/gui/GlutWindow.cpp, dart/gui/Win3D.cpp, dart/gui/Win3D.h
This pull request replaces our own multisample anti-aliasing implementation with [the built-in method in OpenGL](https://www.opengl.org/wiki/Multisampling#Rendering_with_Multisampling), and removes the use of accumulation buffer, which is [deprecated in OpenGL 3.0](https://www.opengl.org/wiki/History_of_OpenGL#Deprecation_Model).
Also, `GLUT_STENCIL` flag is removed since it's not used anywhere.
=> Multisample anti-aliasing

dart/dynamics/Joint.cpp, dart/dynamics/Skeleton.cpp, dart/dynamics/Skeleton.h, unittests/testNameManagement.cpp
A bug was found where renaming a Joint would always alter the DegreeOfFreedom names, even when the user told them not to be renamed. This pull request fixes that issue and introduces a regression test to prevent it from happening again.
=> Fixed bug with renaming Joints and created regression test

dart/dynamics/DegreeOfFreedom.cpp, dart/dynamics/DegreeOfFreedom.h
There were some Joint functions that apply to individual ``DegreeOfFreedom``s which had been missing from the DegreeOfFreedom API.
=> Added some missing API for DegreeOfFreedom

dart/utils/SkelParser.cpp
We were using an iterator without first checking whether it was valid, even though the container will drop down to size 0 by the time the parsing is finished. Now we quit parsing once the container is empty.
=> Remove undefined behavior from SkelParser

dart/constraint/ContactConstraint.h, dart/constraint/SoftContactConstraint.h, dart/dynamics/BodyNode.h, dart/dynamics/Frame.h, dart/dynamics/Inertia.h, dart/dynamics/Joint.h, dart/dynamics/LineSegmentShape.cpp, dart/dynamics/LineSegmentShape.h, dart/dynamics/MultiDofJoint.h, dart/dynamics/ScrewJoint.h, dart/dynamics/TranslationalJoint.h, dart/dynamics/detail/MultiDofJoint.h, dart/math/MathTypes.h, dart/renderer/OpenGLRenderInterface.cpp, dart/renderer/OpenGLRenderInterface.h, dart/renderer/RenderInterface.cpp, dart/renderer/RenderInterface.h, dart/utils/SkelParser.cpp, dart/utils/SkelParser.h, dart/utils/sdf/SdfParser.cpp, dart/utils/sdf/SdfParser.h, dart/utils/sdf/SoftSdfParser.cpp, unittests/testFrames.cpp, unittests/testJoints.cpp
This pull request resolves [memory alignment issues with Eigen objects](http://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__Alignement.html) in DART.
Also, some helper types and functions are defined for convenience such as ```Eigen::aligned_vector``` and ```Eigen::make_aligned_shared()```. One thing I'm not sure is the namespace and names of them. ```dart::aligned_vector``` or ```dart::aligned::vector``` are alternatives I can imagine. Any thought on this?
Related issues: #413
=> Eigen aligned memory allocator

dart/dynamics/detail/MultiDofJoint.h
There was a lot of inconsistency among the format of warning messages for MultiDofJoint functions, even though the warnings they were giving were basically identical: indexing issues. This pull request standardizes (most of) them with two macros.
=> Standardized warning messages for MultiDofJoints

dart/utils/sdf/SdfParser.cpp
Child of a joint was not correctly parsed in SDF files.
=> Correct child for a joint

appveyor.yml
There was [build environment update of Appveyor](http://www.appveyor.com/blog/2015/06/23/new-oss-build-environment-and-xamarin-support) but it causes [a problem installing DART-Prerequisites.msi](). Use [previous worker images](http://www.appveyor.com/updates/2015/06/20) until it's resolved.
=> Fix Appveyor build

dart/dynamics/SingleDofJoint.cpp, dart/dynamics/detail/MultiDofJoint.h
Similar to the previous changes for MultiDofJoints, I've standardized and improved the warnings for SingleDofJoints.
This also fixes a bug that caused warning messages when a zero-valued command was set for passive actuators.
=> Improved joint warnings for Single and MultiDofJoints

CMakeLists.txt, package.xml
This pull request: (1) [adds a `package.xml`](http://www.ros.org/reps/rep-0136.html#having-a-catkin-package-xml) file for DART and (2) [installs it to `share/dart`](http://www.ros.org/reps/rep-0136.html#installing-a-catkin-package-xml). These are the minimal requirements, from [REP-136](http://www.ros.org/reps/rep-0136.html) to build a third-party package as part of a Catkin workspace.
I am generally not a fan of putting these type of files in  non-ROS packages, so I make this pull request with some trepidation. However, this is very useful if you are developing DART in parallel with ROS packages (e.g. the work I mentioned on `DartLoader`) because: (1) it allows you to easily link against DART without installing it into a system directory, (2) automatically re-builds DART when it is …
=> Added a package.xml file for REP-136 support

dart/utils/sdf/SdfParser.cpp, dart/utils/sdf/SdfParser.h, data/sdf/test/single_bodynode_skeleton.world, unittests/testParser.cpp
The SDF parser currently assumes there is at least one Joint in the model, so it fails to correctly parse a model that has no Joints (i.e. all bodies are root nodes).
This pull request fixes that issue, and should be more robust in general because it iterates through bodies instead of joints when constructing a Skeleton.
=> More robust SDF parsing -- Patch for Release 5.0

dart/dynamics/Chain.cpp, dart/dynamics/Chain.h, dart/dynamics/Linkage.cpp, dart/dynamics/Linkage.h, unittests/testSkeleton.cpp
This pull request addresses issue #437 and replaces pull request #440.
The changes are as follows:
* You can now tell specify in your Linkage Criteria that a start or a target BodyNode should be *excluded* from the Linkage.
* The new default behavior for Chains is that whichever BodyNode is upstream of the other will be excluded from the Chain
* An alternative constructor is available for Chains which allows the user to request that both the start and the target BodyNodes should be included, regardless of which is upstream
* Linkage and Chain criteria now allow you to specify a nullptr starting BodyNode, which will be treated as if it represents the World
=> Changes to Linkage and Chain Criteria

dart/dynamics/MeshShape.cpp, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/DartLoader.h, data/urdf/test/invalid.urdf, data/urdf/test/invalid_mesh.stl, data/urdf/test/invalid_mesh.urdf, data/urdf/test/missing_mesh.urdf, data/urdf/test/missing_package.urdf, data/urdf/test/primitive_geometry.urdf, unittests/testDartLoader.cpp, unittests/testSdfParser.cpp, unittests/testSkelParser.cpp
DartLoader currently SEGFAULTs if it fails loading a mesh and, possibly, in a few other situations. This pull request adds error-handling logic that prints a `dterr` message and returns `nullptr` in that case.
=> Fixed SEGFAULTs in DartLoader

debian/control
This retargets #455 for 5.0.1. See #451 for details.
=> Require Assimp < 3.0~dfsg-4 -- Patch for Release 5.0

dart/dynamics/Skeleton.cpp, dart/dynamics/Skeleton.h
This pull request adds an `std::mutex` to `Skeleton`. Most of the methods on `Skeleton` are not thread safe, so using some kind of mutex is necessary in a multi-threaded application. It's useful to attach the mutex to `Skeleton` so you don't have to manually pass one around to every function that operates on it.
=> Added a mutex to Skeleton.

dart/dynamics/DegreeOfFreedom.cpp, dart/dynamics/DegreeOfFreedom.h, dart/dynamics/Joint.cpp, dart/dynamics/Joint.h, dart/dynamics/MultiDofJoint.h, dart/dynamics/SingleDofJoint.cpp, dart/dynamics/SingleDofJoint.h, dart/dynamics/ZeroDofJoint.cpp, dart/dynamics/ZeroDofJoint.h, dart/dynamics/detail/MultiDofJoint.h, dart/utils/SkelParser.cpp, dart/utils/sdf/SdfParser.cpp, dart/utils/urdf/DartLoader.cpp, unittests/testParser.cpp
There are now properties that can be given to the joints of a robot for initial position and initial velocity. Calling the ``resetPosition`` and ``resetVelocity`` functions will set the joint to its initial position and velocity respectively, instead of zeroing them out. By default, these properties are zero.
The SkelParser will set these properties based on the initial positions and velocities given in the ``.skel`` file. However, neither the URDF nor the SDF parsers support this, because I could not find a relevant tag in either of those formats.
=> Added initial position and initial velocity properties

dart/dynamics/MeshShape.cpp, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/DartLoader.h, data/urdf/test/invalid.urdf, data/urdf/test/invalid_mesh.stl, data/urdf/test/invalid_mesh.urdf, data/urdf/test/missing_mesh.urdf, data/urdf/test/missing_package.urdf, data/urdf/test/primitive_geometry.urdf, unittests/testDartLoader.cpp, unittests/testSdfParser.cpp, unittests/testSkelParser.cpp
This backports #439 to DART 5.0 for the upcoming 5.0.1 release in #467.
=> Fixed SEGFAULTs in DartLoader -- Patch for Release 5.0

CMakeLists.txt, Changelog.md, debian/changelog
DART 5.0.1 release includes patches for the bugs we found in DART 5.0.0. 
[DART 5.0.1 will be used in Gazebo 6.0](https://bitbucket.org/osrf/gazebo/pull-request/1825/dart-interface-update-for-dart-50/diff).
=> Packaging DART 5.0.1

doxygen/Doxyfile.in
This pull request removes the list of local source files at the bottom of generated documentation.
=> Remove list of local source files from generated doxygen documentation

apps/atlasSimbicon/State.cpp, dart/collision/bullet/BulletTypes.h, unittests/testSdfParser.cpp
This pull request fixes:
* signed/unsigned mismatch warnings in atlasSimbicon app and testSdfParser
* build error reported by #418.
The unused-variable-warnings from bullet are now suppressed by [adding SYSTEM flag to include_directories](https://github.com/dartsim/dart/pull/435) instead of [problematic dummy functions](https://github.com/dartsim/dart/commit/3e7565870bb5c135b49ee6ba931ecb03c49e7448).
=> Fix compilation warnings and build error

ci/before_install_linux.sh, ci/before_install_osx.sh, dart/optimizer/ipopt/IpoptSolver.cpp, dart/optimizer/ipopt/IpoptSolver.h, unittests/testOptimizer.cpp
This pull request is a revised version of #198 with more bug fixes.
=> Fix IpoptSolver bugs

CMakeLists.txt
This pull request sets the [`CMP0042` policy](http://www.cmake.org/cmake/help/v3.0/policy/CMP0042.html) in CMake:
> MACOSX_RPATH is enabled by default.
>
> CMake 2.8.12 and newer has support for using `@rpath` in a target’s install name. This was enabled by setting the target property MACOSX_RPATH. The `@rpath` in an install name is a more flexible and powerful mechanism than @executable_path or `@loader_path` for locating shared libraries.
>
> CMake 3.0 and later prefer this property to be ON by default. Projects wanting `@rpath` in a target’s install name may remove any setting of the INSTALL_NAME_DIR and CMAKE_INSTALL_NAME_DIR variables.
>
> This policy was introduced in CMake version 3.0. CMake version 3.0.2 warns when the policy is not set and uses OLD behavior. Use the cmake_policy …
=> Fixed CMake warnings

dart/utils/sdf/SdfParser.cpp, dart/utils/urdf/DartLoader.cpp
This pull request fixes the bug that I fixed in #438. This was intended to be fixed with the addition of `mInitialPositions` in #449. However, that pull request only sets `mInitialPositions`, not `mRestPositions`, in the URDF and SDF loaders.
This pull request restores the same logic to `mRestPositions`.
=> Initialize mRestPosition if zero is not in range.

osgDart/CMakeLists.txt
I needed to add these to get `osgDart` to build on OS X.
*Note:* This is a pull request into the `grey/osg` branch, not `master`.
=> Added missing target_link_libraries to osgDart

dart/dynamics/BodyNode.cpp, dart/dynamics/BodyNode.h, dart/dynamics/Joint.cpp, unittests/testForwardKinematics.cpp
This is a bug fix and regression test for release-5.0 which fixes issue #499.
Thanks to Nathan Ratliff for bringing this issue to our attention!
=> Dirtying Jacobian update flags whenever the parent transform is changed -- Release 5.0 patch

dart/dynamics/FreeJoint.h, dart/dynamics/SimpleFrame.h
I thought it would be good to default the ``relativeTo`` parameters for the ``setTransform`` functions of ``SimpleFrame`` and ``FreeJoint``.
=> Give default Frame::World parameters to setTransform functions

dart/math/Helpers.h
[Visual Studio 2013 doesn't support `constexpr` specifier yet](https://msdn.microsoft.com/en-us/library/vstudio/hh567368(v=vs.120).aspx).
=> Don't use constexpr for vs2013

ci/appveyor_install.ps1, dart/utils/urdf/urdf_world_parser.cpp
The DART prerequisites installer for Windows was updated to use newer version of urdfdom (0.3.0). This PR updates the script for AppVeyor CI to install the updated one. This should resolve the issue of missing `urdf::parsePose` reported by @jturner65.
=> Use urdfdom 0.3.0 for AppVeyor CI tests

dart/dynamics/BodyNode.h, dart/dynamics/EndEffector.h
We can devirtualize the Jacobian function calls for ``BodyNode`` and ``EndEffector`` by using the ``final`` keyword on their Jacobian function implementations.
=> Enable compiler optimization by using 'final' keyword for Jacobian functions

dart/config.h.in, dart/lcpsolver/common.h, dart/lcpsolver/odeconfig.h, tutorials/tutorialBiped-Finished.cpp, tutorials/tutorialCollisions-Finished.cpp, tutorials/tutorialCollisions.cpp
This PR:
* removes macros for some c99 library functions in odeconfig.h
* The macros was required since old Visual Studio does not support those functions; they have similar implementation in Visual Studio but they are not in std namespace and have slightly different names
* Visual Studio 2013 and after support those functions and now these macros cause compilation errors because of the namespace issue. For example, std::nextafter(~) will be modified by the macro to std::_nextafter(~) but _nextafter(~) is not in std namespace.
* removes use of deprecated function
* removes duplicated header inclusion
Note that AppVeyor CI build test wouldn't pass since #488 has not addressed yet.
=> Fix compilation errors and warnings on Windows

dart/dynamics/MeshShape.cpp, dart/renderer/OpenGLRenderInterface.cpp
It seems [we started to set the material index to -1 to indicate no material](https://github.com/dartsim/dart/commit/6b0266cfad6aad4cdc40befdf8d5994479a78491#diff-ed1bdc3b52a7df5f3d58c16da27962e4R262). This is correctly handled by osgDart but it was not applied to OpenGLRenderInterface. This should fix segfault of simpleFrames app.
=> Don't use material if the material index is -1 in OpenGLRenderInterface

dart/dynamics/BodyNode.h, dart/dynamics/Entity.h, dart/dynamics/Frame.h, dart/dynamics/Joint.h, dart/dynamics/MetaSkeleton.h, dart/dynamics/Skeleton.h
As pointed out by @mkoval in issue #524, we neglected to delete the copy constructors of various classes that are not copy-safe. This pull request deletes their copy constructors.
=> Fix Copy Safety

unittests/testDynamics.cpp
This PR fixes segfaults on 32-bit systems ([trusty](https://launchpadlibrarian.net/221507472/buildlog_ubuntu-trusty-i386.dart_5.1.0.ppa4~trusty_BUILDING.txt.gz), [vivid](https://launchpadlibrarian.net/221507681/buildlog_ubuntu-vivid-i386.dart_5.1.0.ppa4~vivid_BUILDING.txt.gz)).
=> Aligning a map with fixed-size vectorizable Eigen structs in testDynamics

dart/common/LocalResource.cpp
`ftell` returns `LONG_MAX` as an error code, instead of `-1L` as specified in the documentation, when invoked on a directory. This behavior occurs on EXT4 filesystems, not but NFSv4 file systems, in kernel version 3.16.0 possibly with Ubuntu-specific patches applied (tested in Ubuntu 14.04).
This was not a fun one to debug. :sweat:
=> Workaround for ftell bug in Linux

ci/before_install_osx.sh
This PR reduces Travis-CI build log on Mac based on the idea of:
* https://github.com/osrf/homebrew-simulation/commit/f3cad8c9ab2639d5981418b96002d02a1d6955ea
* https://github.com/travis-ci/travis-ci/issues/4936
=> Reduce Travis-CI build log on Mac

package.xml
DART is using bullet for collision detection, but bullet wasn't listed in the package.xml file.
=> package.xml: depend on bullet

dart/common/LocalResourceRetriever.cpp, dart/common/LocalResourceRetriever.h, dart/common/ResourceRetriever.h, dart/utils/CompositeResourceRetriever.cpp, dart/utils/CompositeResourceRetriever.h, dart/utils/PackageResourceRetriever.cpp, dart/utils/PackageResourceRetriever.h, unittests/TestHelpers.h
This pull request reverts the const-qualification on the ResourceRetriever methods introduced by #517.
Please see #532 for more details.
=> Remove const qualifier of ResourceRetriever methods

osgDart/CMakeLists.txt
This pull request makes `osgDart` obey the `DART_BUILD_EXAMPLES` variable.
=> Made osgDart honor DART_BUILD_EXAMPLES

dart/dynamics/InverseKinematics.h, dart/dynamics/MeshShape.h, dart/optimizer/nlopt/NloptSolver.h
This pull request adds several missing `override` keywords that produce warnings in clang 3.7. I also removed a few `virtual` keywords on functions methods that are flagged as `override`. [The `virtual` keyword has no effect if you're overriding a `virtual` function](http://stackoverflow.com/a/29760395/111426), so this is not necessary. It also seems to be the style used in the majority of DART.
=> Added missing 'override' keywords

dart/dynamics/DegreeOfFreedom.h, dart/dynamics/EulerJoint.h, dart/dynamics/FreeJoint.h, dart/dynamics/MultiDofJoint.h, dart/dynamics/PlanarJoint.h, dart/dynamics/PrismaticJoint.h, dart/dynamics/RevoluteJoint.h, dart/dynamics/ScrewJoint.h, dart/dynamics/TranslationalJoint.h, dart/dynamics/UniversalJoint.h, dart/dynamics/WeldJoint.h, dart/dynamics/ZeroDofJoint.h
Same as #538 , but it's a patch for 5.1.
=> Delete copy constructors for non-copyable classes (round 2) -- Patch for 5.1

dart/dynamics/DegreeOfFreedom.h, dart/dynamics/EulerJoint.h, dart/dynamics/FreeJoint.h, dart/dynamics/MultiDofJoint.h, dart/dynamics/PlanarJoint.h, dart/dynamics/PrismaticJoint.h, dart/dynamics/RevoluteJoint.h, dart/dynamics/ScrewJoint.h, dart/dynamics/TranslationalJoint.h, dart/dynamics/UniversalJoint.h, dart/dynamics/WeldJoint.h, dart/dynamics/ZeroDofJoint.h
Some invalid copy constructors were neglected with the last pull request, so this pull request deletes more of them.
=> Delete copy constructors for non-copyable classes (round 2)

dart/dynamics/BodyNode.cpp, dart/dynamics/BodyNode.h
This pull request fixes const correctness of `BodyNode::getMomentOfInertia()` as reported in #540.
=> Fix const correctness of BodyNode::getMomentOfInertia()

dart/common/Deprecated.h, dart/config.h.in, dart/optimizer/Function.cpp
For backward compatibility, we have to call deprecated functions in Function.cpp, but the compilers complain for these calls. This pull request suppresses the warnings only for those calls. See also #544.
Note that the suppression code couldn't be made as macros. It needs to use compiler dependent #pragma directives but directives is not allowed to be declared in macros.
=> Suppress warnings in Function.cpp

dart/dynamics/Group.cpp, dart/dynamics/Group.h, dart/dynamics/Linkage.cpp, dart/dynamics/ReferentialSkeleton.cpp, dart/dynamics/ReferentialSkeleton.h, dart/dynamics/detail/JointPtr.h, unittests/testSkeleton.cpp
This pull request is in response to issues #548 and #556. This fixes the issue where BodyNodes with zero-dof parent Joints will be left out of ReferentialSkeletons, and it allows users to add and remove BodyNodes and DegreesOfFreedom from Groups freely (i.e. without any coupling between BodyNodes and their parent DegreesOfFreedom).
However, in the current implementation there is still a 1-to-1 correspondence between BodyNodes and Joints, even though BodyNodes are decoupled from DegreesOfFreedom. What this means is that ``ReferentialSkeleton::getJoint(i)`` is always equivalent to ``ReferentialSkeleton::getBodyNode(i)->getParentJoint()``. This is despite the fact that there is no coupling between ``ReferentialSkeleton::getBodyNode(~)`` and ``ReferentialSkeleton::getDof(~)``.
So I before …
=> Improvements to ReferentialSkeleton

dart/CMakeLists.txt, debian/libdart-core5-dev.install, debian/libdart5-dev.install
This pull request fixes incorrect packaging of `dart-core` and `dart`.
`dart-core` library should contain following namespaces:
* common
* math
* integration
* lcpsolver
* dynamics
* optimizer
* collision
* constraint
* renderer
* simulation
and `dart` library should contain following namespaces:
* `dart-core`
* gui
* planning
* utils
=> Fix packaging of dart-core/dart libraries

CMakeLists.txt
I felt that the wording of the cmake warning messages for ASSIMP might be difficult to understand, so I attempted to improve their clarity a bit.
=> Improved wording of the cmake warning messages for ASSIMP

Changelog.md, debian/changelog, debian/control
Fix for missing `liburdfdom-dev` dependency. See #571.
Should I add something to the changelog?
=> Fix control file for missing urdfdom-dev dep

docs/readthedocs/tutorials/collisions.md, tutorials/tutorialMultiPendulum.cpp
There is some code in lesson 2a of Pendulum:
for(size_t i = 0; i < mPendulum->getNumDofs(); ++i)
{
DegreeOfFreedom* dof = mPendulum->getDof(i);
double q0 = dof->getRestPosition() + delta;
dof->setRestPosition(q0);
}
the variable delta may be the parameter of the functions, but the tutorial don't say where the variable 'delta' comes from.
http://dart.readthedocs.org/en/release-5.1/tutorials/multi-pendulum/#lesson-2a-set-joint-spring-rest-position
User may need read the finished file and get hints.
There is a typo error in collision.md
=> add more hint to Pendulum.cpp, revise the typo error in collision.md

dart/dynamics/Entity.cpp, dart/dynamics/Frame.cpp, unittests/testConcurrency.cpp
This pull request is meant to fix the segmentation fault reported in issue #576 . I managed to create a unittest which reliably triggered a race condition which I hope corresponds to the race condition reported in #576.
=> Fix World Concurrency

.travis.yml, ci/before_install_linux.sh, dart/constraint/JointCoulombFrictionConstraint.cpp, dart/constraint/JointLimitConstraint.cpp, unittests/testJoints.cpp
This pull request fixes #317 for DART 5.1 as fixed in #566 for DART 6.0.
=> Fix incorrect applying of joint constraint impulses --  Patch for 5.1

CMakeLists.txt, dart/constraint/ConstrainedGroup.h, dart/dynamics/Skeleton.h, dart/math/Helpers.h, dart/utils/urdf/urdf_world_parser.cpp
This pull request fixes all the build errors that I encountered while trying to build DART with Visual Studio 2015.
CMake would fail to configure if you weren't using exactly Visual Studio 2013, so I added a conditional for 2015 as well.
=> Fix Visual Studio 2015 build errors

apps/atlasSimbicon/Controller.cpp, apps/atlasSimbicon/Controller.h, apps/jointConstraints/MyWindow.cpp, apps/jointConstraints/MyWindow.h, apps/rigidLoop/Main.cpp, dart/common/SmartPointer.h, dart/constraint/ConstrainedGroup.cpp, dart/constraint/ConstrainedGroup.h, dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.h, dart/constraint/DantzigLCPSolver.cpp, dart/constraint/PGSLCPSolver.cpp, dart/constraint/SmartPointer.h, dart/dynamics/SmartPointer.h, docs/readthedocs/tutorials/collisions.md, docs/readthedocs/tutorials/multi-pendulum.md, tutorials/tutorialCollisions-Finished.cpp, tutorials/tutorialCollisions.cpp, tutorials/tutorialMultiPendulum-Finished.cpp
This change is motivated by issue #583 where it was found that the ``ConstraintSolver`` class is leaking memory. Frequent deletion and creation of ``World`` objects can dramatically exacerbate the issue. By updating to use C++11 smart pointers, we should be able to eliminate these leaks.
=> Updating the constraint namespace to C++11

dart/dynamics/ArrowShape.cpp, dart/dynamics/MeshShape.cpp, dart/dynamics/MeshShape.h
I found that there is a risk of segmentation fault for meshes that are not immediately initialized. It occurs when the Mesh::_updateBoundingBoxDim function is called. This pull request fixes this issue, and adds some more initialization for ``ArrowShape``.
=> Fixed segmentation fault for null meshes

dart/constraint/ConstrainedGroup.cpp, dart/constraint/ConstrainedGroup.h
This pull request implements a missing implementation in ConstrainedGroup as reported in #584 and removes a private method ConstrainedGroup::checkAndAddConstraint() as it's not being called anywhere. Also, this makes ConstrainedGroup::containConstraint() to be compiled only in debug mode.
=> Implement missing implementation in ConstrainedGroup

CMakeLists.txt, README.md, appveyor.yml, ci/appveyor_install.ps1, dart/common/Addon.h, dart/common/AddonManager.cpp, dart/common/AddonManager.h, dart/common/detail/AddonManager.h, dart/dynamics/Joint.cpp, dart/dynamics/Joint.h, dart/dynamics/MultiDofJoint.h, unittests/testJoints.cpp
This pull request
* merges master branch into #531 (should pass appveyor tests)
* revises as discussed in #531
=> Revision of #531

dart/utils/VskParser.cpp, dart/utils/VskParser.h
This pull request updates VskParser for following extentions:
- `<Shape>` tag to change the shape of the character
- `DENSITY` properties to `<Skeleton>` tag
- `MASS` properties to `<Segment>` tag
- an option to remove the redundant *end* segments.
The original work was done by @sehoonha .
=> Improve VSK parser with extensions

dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.h, dart/utils/SkelParser.cpp
`constraint::ConstraintSolver` takes ownership of the `setCollisionDetector` passed in to `setCollisionDetector`. This is not clear from the API because the function accepts a raw pointer. This leads to a SEGFAULT if you do not expect `ConstraintSolver` to delete your `CollisionDetector`.
I modified `setCollisionDetector` to take an `unique_ptr` to make the ownership transfer explicit. I also switched to storing the `LCPSolver` in a `unique_ptr` to remove the other manual `delete` from the `ConstraintSolver` destructor.
=> Made ConstraintSolver obey C++11 ownership conventions

dart/dynamics/BoxShape.h, dart/dynamics/CylinderShape.h, dart/dynamics/EllipsoidShape.h, dart/dynamics/PlaneShape.h, dart/dynamics/SoftMeshShape.h
This fixes a bunch of `-Winconsistent-missing-override` warnings in Clang 3.7.
=> Added missing override specifiers on draw() methods

dart/gui/GlutWindow.cpp
This fixes #395 thanks to @olzhas.
=> Create 'frames' directory if not exists for screenshot

dart/dynamics/MetaSkeleton.h, dart/dynamics/ReferentialSkeleton.h, dart/dynamics/Skeleton.h, unittests/testSkeleton.cpp
This fixes the ambiguous overload that was reported in #626 .
=> Fix for issue #626

dart/common/Addon.h, dart/common/AddonManager.h, dart/common/AddonManagerJoiner.h, dart/common/RequiresAddon.h, dart/common/SpecializedForAddon.h, dart/common/detail/AddonManager.h, dart/common/detail/RequiresAddon.h, dart/common/detail/SpecializedAddonManager.h, dart/common/detail/SpecializedForAddon.h, dart/dynamics/Addon.h, dart/dynamics/BodyNode.h, dart/dynamics/EndEffector.h, dart/dynamics/MultiDofJoint.h, dart/dynamics/SingleDofJoint.cpp, dart/dynamics/SingleDofJoint.h, dart/dynamics/Skeleton.h, dart/dynamics/SpecializedNodeManager.h, dart/dynamics/detail/Addon.h, dart/dynamics/detail/MultiDofJointProperties.h, dart/dynamics/detail/PlanarJointProperties.h, dart/dynamics/detail/PrismaticJointProperties.h, dart/dynamics/detail/RevoluteJointProperties.h, dart/dynamics/detail/ScrewJointProperties.h, dart/dynamics/detail/SingleDofJointProperties.h, dart/dynamics/detail/SpecializedNodeManager.h, dart/dynamics/detail/UniversalJointProperties.h, unittests/testAddon.cpp
In the current implementation of "optionality" for Addons, it is an Addon that decides for itself whether it is optional for a given Manager type. This is semantically backwards, since the Manager owns the Addon and should therefore have authority over whether the Addon is considered optional or required.
This pull request reverses this relationship. Now a Manager can specify which Addons are required for it in a similar fashion to how Addons can be specialized for it. In fact, declaring an Addon as "required" will also automatically specialize the Addon for that Manager.
=> Changing authority of Optional/Required Addons

.travis.yml, CMakeLists.txt, README.md, ci/before_install_linux.sh, ci/script_linux.sh, cmake/Coveralls.cmake, cmake/CoverallsClear.cmake, cmake/CoverallsGenerateGcov.cmake, dart/CMakeLists.txt
This pull request adds code coverage testing for DART. [`coveralls`](https://coveralls.io/) is used to show the results on the website with nice charts and tables. External cmake scripts ([`coveralls-cmake`](https://github.com/JoakimSoderberg/coveralls-cmake)) are imported to generate and upload coverage data to `coveralls`.
=> Code coverage test

cmake/CoverallsGenerateGcov.cmake
This is confirmed by the upstream. [Issue](https://github.com/JoakimSoderberg/coveralls-cmake/issues/12) and [PR](https://github.com/JoakimSoderberg/coveralls-cmake/pull/13).
=> Fix invalid coveralls report file generation with multiline commit message

dart/constraint/DantzigLCPSolver.cpp
The code previously checked for `getNumConstraints() == 0`, but not `getTotalDimension() == 0`. This caused the LCP solver to access invalid memory if constraints were present, but all constraints had `getDimension() == 0`. I ran into this using a `ServoJointConstraint` in a completely empty environment.
Thanks @jslee02 for helping me debug this.
=> Fixed DantzigLCPSolver when getTotalDimension = 0

CMakeLists.txt, cmake/config.h.in, dart/constraint/ConstraintSolver.cpp
DART currently uses `FCLMeshCollisionDetector` by default because FCL < 0.4 returns incorrect contact points for some primitive-primitive collision checks. This pull request changes the behavior in two ways:
1. Prints a warning about the bug if CMake detects an old version of FCL.
2. Uses `FCLCollisionDetector`, instead of `FCLMeshCollisionDetector`, if a new version if FCL is found.
=> Use FCLCollisionDetector by default if version >= 0.4 is available

CMakeLists.txt
This fixes #625 by removing the test for a Bullet version. This is important because Ubuntu 14.04 ships with Bullet 2.81, which fails the version check for Bullet 2.82 in the current DART `master`.
I would prefer to remove the check entirely, instead of simply lowering to Bullet 2.81, because we have no evidence to believe that the interface will not work on earlier versions of Bullet. We can re-introduce a version check if we find a compelling reason to do so (e.g. DART fails to build against very old versions).
I also removed the logic that uses `pkg-config` on `UNIX` systems. The `find_package` command works fine for me on Linux and was unable to find a justification for these gymnastics in the `git` history.. Does anyone know why this check was introduced?
=> Removed version check for Bullet.

CMakeLists.txt, apps/rigidShapes/Main.cpp, dart/common/StlHelpers.h, dart/common/detail/AddonWithVersion.h, dart/common/detail/Extensible.h, dart/dynamics/BodyNode.cpp, dart/dynamics/EndEffector.cpp, dart/dynamics/InverseKinematics.cpp, dart/optimizer/nlopt/NloptSolver.cpp, osgDart/InteractiveFrame.cpp, osgDart/examples/osgHuboPuppet.cpp, tutorials/tutorialBiped-Finished.cpp, tutorials/tutorialBiped.cpp, tutorials/tutorialDominoes-Finished.cpp, tutorials/tutorialDominoes.cpp, unittests/testAddon.cpp, unittests/testConstraint.cpp
This pull request adds `make_unique` function as suggested in #633 .
=> Add make_unique function omitted from C++11

dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.h
There is currently no way to use anything other than the default LCP solver in `ConstraintSolver`. This pull request adds functions that parallel the `get/setCollisionDetector` for the `LCPSolver`.
=> Added get/setLCPSolver functions to ConstraintSolver

dart/optimizer/ipopt/CMakeLists.txt, dart/optimizer/nlopt/CMakeLists.txt, dart/optimizer/snopt/CMakeLists.txt
Merging #630 uncovered some latent issues in DART's CMake configuration. The optional `dart::optimizer` components (bindings for `nlopt`, `ipopt`, and `snopt`) were not being added to the `DARTTargets` group and, thus, were not included in `DARTTargets.cmake`. This caused finding those components, e.g. via `find_package(DART COMPONENTS nlopt)`, to fail even if they were built.
I thought the same issue would be present with `FCLCollisionDetector` and `BulletCollisionDetector`, but it appears that all of the available collision detectors are being linked into `dart.so`. There is dead code in those `CMakeLists.txt` file that indicates this was not always the case.
I found this surprising because merging all of these into one library seems undesirable. Was this an intentional change?
=> Fixed find_package(DART) on optimizer components

dart/common/StlHelpers.h, dart/lcpsolver/ODELCPSolver.cpp, dart/optimizer/ipopt/IpoptSolver.cpp
Building DART in release mode disables assertions. There are a few parameters in DART that are only used in assertions, so this generates `-Wunused-parameter` warnings. This pull request adds a `DART_UNUSED` that suppresses those warnings. See [this StackOverflow answer](http://stackoverflow.com/a/777359/111426) for more explanation.
=> Suppress unused variables warnings in release mode

unittests/testOptimizer.cpp
It seems like this was overlooked from pull request #641. This change was necessary for me to successfully compile.
=> Needed to change #ifdef to #if

CMakeLists.txt, apps/CMakeLists.txt, appveyor.yml, ci/script_linux.sh, ci/script_osx.sh, osgDart/CMakeLists.txt, osgDart/examples/CMakeLists.txt, tutorials/CMakeLists.txt, unittests/CMakeLists.txt
This pull request replaces the `DART_BUILD_UNITTESTS`, `DART_BUILD_EXAMPLES` and `DART_BUILD_TUTORIALS` CMake flags the `tests`, `examples`, and `tutorials` targets. These features are no longer built by default unless the user explicitly passes the corresponding target(s) to `make`. 
The key advantage of this approach is that targets are specified at *build time*, whereas CMake flags are specified at *configure time*. These features are optional and take a long time to build, so I prefer having them disabled by default. It's currently awkward to do this because changing these settings requires re-running CMake with new `-D` flags and, possibly, deleting your `CMakeCache.txt` file.
With the new paradigm, this is as simple as running `make` during development and passing the `tests`, …
=> Split tutorials, examples, and tests into separate targets

dart/utils/sdf/SdfParser.cpp, unittests/testSdfParser.cpp
This fixes SdfParser fails to load mesh files, which was reported by @sehoonha .
=> Assign resource retriever when nullptr passed to SdfParser

CMakeLists.txt, cmake/DARTFindDependencies.cmake, dart/CMakeLists.txt, dart/gui/CMakeLists.txt, dart/gui/osg/render/CMakeLists.txt
I removed OpenGL (and renderer) libs/includes from main library (libdart) and moved them to gui library (lib-dart-gui). Also, I minor fix for installing properly the gui-osg include files..
=> Removing OpenGL dep from main lib

dart/constraint/ConstraintSolver.cpp, dart/dynamics/MetaSkeleton.h, dart/dynamics/ReferentialSkeleton.cpp, dart/dynamics/ReferentialSkeleton.h, dart/dynamics/Skeleton.cpp, dart/dynamics/Skeleton.h
Fixes #666 issue. It's done quickly and dirty. So feel free to not accept or polish it. It's just that we are using this functionality and needed it asap, so I coded it and sharing it..
Many thanks..
=> Fixes collision problem

dart/collision/Contact.cpp, dart/collision/Contact.h, dart/collision/Result.cpp, dart/collision/Result.h, dart/collision/dart/DARTCollide.cpp, dart/collision/dart/DARTCollide.h, dart/collision/dart/DARTCollisionDetector.cpp, dart/dynamics/BodyNode.h, dart/dynamics/MetaSkeleton.h, dart/dynamics/ReferentialSkeleton.h, dart/dynamics/ShapeFrame.h, dart/dynamics/ShapeNode.cpp, dart/dynamics/Skeleton.h, dart/simulation/World.cpp, dart/simulation/World.h, unittests/testCollision.cpp
This pull request addresses the discussion in PR #668
=> Adding collision sets to CollisionResult

dart/dynamics/HierarchicalIK.cpp, dart/dynamics/InverseKinematics.cpp, dart/dynamics/InverseKinematics.h
This comment might be a bit helpful to understand how IK problem is solved internally especially about what is the initial guess and how seeds are used.
=> Add more description on InverseKinematics::solve()

Changelog.md, debian/changelog, debian/control
All the invalid changes for DART 6.0 are ignored.
=> Merge 4.3.6 into master

CMakeLists.txt, dart/constraint/BalanceConstraint.cpp, dart/dynamics/BodyNode.cpp, dart/dynamics/EndEffector.cpp, dart/dynamics/InverseKinematics.cpp, dart/dynamics/Skeleton.cpp, package.xml, unittests/testForwardKinematics.cpp
This fixes the issues reported in #683, but it's targeted at ``release-5.1``, and it does not have any changes to the ABI.
Inverse kinematics and ``EndEffector``s were introduced in 5.1, so this is the only release that needs to be patched.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/684)
=> Fixing Inverse Kinematics for 5.1

CMakeLists.txt, doxygen/Doxyfile.in
[Doxygen tag files is used to link to external documentation](https://www.stack.nl/~dimitri/doxygen/manual/external.html). This would be useful for the external project that depends on DART.
The url of the tag file is http://dartsim.github.io/dart/dart.tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/690)
=> Generate doxygen tag file

CMakeLists.txt, cmake/DARTConfig.cmake.in, cmake/DARTCoreConfig.cmake.in
This PR includes two patches of #630 and 697 for DART 5.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/696)
=> Backporting of #630 and #697 for 5.1

CMakeLists.txt, cmake/DARTConfig.cmake.in
The fix from #361 doesn't work if bullet package was failed to be found by `find_package()`. When bullet is not found, `BULLET_INCLUDE_DIRS` will be set to `BULLET_INCLUDE_DIRS-NOT-FOUND` rather than blank as we assumed in #361.
Instead, we set `DART_INCLUDE_DIRS` in the top level CMakeList.txt by adding `BULLET_INCLUDE_DIRS` to `DART_INCLUDE_DIRS` only when bullet is found. `DARTConfig.cmake` is then configured using `DART_INCLUDE_DIRS`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/697)
=> Fix BULLET_INCLUDE_DIRS in DARTConfig.cmake

Changelog.md, debian/changelog, debian/control
Waiting Launchpad buildings:
* trusty: [i386](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/9627598), [amd64](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/9627597)
* wily: [i386](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/9627604), [amd64](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/9627603)
* xenial: [i386](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/9627606), [amd64](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/9627605)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/698)
=> Packaging 5.1.2

dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/689)
=> Make ConstraintSolver to return CollisionDetector/CollisionGroup as shared pointer

dart/dynamics/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/706)
=> Fixed a CMake typo that was preventing dynamics/detail headers from being installed

dart/common/Cloneable.hpp, dart/common/detail/Cloneable.hpp, dart/common/detail/CompositeData.hpp, unittests/testAspect.cpp
Up until now, ``Composite::State`` and ``Composite::Properties`` has had a ``copy(~)`` function which will do a deep copy making the contents of one instance exactly the same as the contents of another instance.
This PR adds a ``merge`` function which will allow the receiving instance to hang onto any entries it has which are not present in the sending instance. So suppose we have:
```
Composite::Properties receiver, sender;
sender.create<Aspect1>();
receiver.create<Aspect2>();
receiver.merge(sender);
```
Then ``receiver`` will get the ``Aspect1`` contents of ``sender``, but it will also get to keep its own ``Aspect2`` contents. On the other hand if we used ``receiver.copy(sender)`` instead, then ``receiver`` would lose its ``Aspect2`` contents in order to be a perfect duplicate of …
=> merge(~) feature for Composite State and Properties

dart/collision/CollisionGroup.cpp, dart/collision/CollisionGroup.hpp, unittests/testCollision.cpp
I wanted to be able to make deep clones of ``CollisionGroup``s, so I've added the ability to access the ShapeFrames of a ``CollisionGroup``. The deep clone will still need to be done manually by the user for the time being for a variety of reasons, such as:
1. ``ShapeFrame`` ownership is still a complex issue without a decisive solution.
2. The deeply cloned ``CollisionGroup`` will probably need to belong to a different ``CollisionDetector``, since the motive for deep cloning is usually multi-threading, and I can't think of an obvious API for automating this right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/711)
=> Added function to retrieve ShapeFrames from CollisionGroups

dart/common/Aspect.cpp, dart/common/Aspect.hpp, dart/common/AspectWithVersion.hpp, dart/common/Composite.cpp, dart/common/EmbeddedAspect.hpp, dart/common/ProxyAspect.hpp, dart/common/detail/Aspect.hpp, dart/common/detail/AspectWithVersion.hpp, dart/common/detail/Composite.hpp, dart/common/detail/EmbeddedAspect.hpp, dart/common/detail/ProxyAspect.hpp, dart/common/detail/SpecializedForAspect.hpp, dart/dynamics/ShapeFrame.cpp, dart/dynamics/ShapeFrame.hpp, unittests/testAspect.cpp
This addresses #712 and lifts the arbitrary requirement that every ``Aspect`` be created within a ``Composite``.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/713)
=> Removing the requirement that Aspects are created within Composites

CHANGELOG.md, CMakeLists.txt, dart/collision/dart/DARTCollide.cpp, dart/collision/dart/DARTCollide.hpp, package.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/722)
=> Add warnings for unsupported shape pairs of DARTCollisionDetector

dart/dynamics/Skeleton.cpp, unittests/testSkeleton.cpp
The total mass of a Skeleton was not getting updated when a body is removed. This fixes the problem and introduces a regression test for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/731)
=> Update total mass when removing bodies

CHANGELOG.md, dart/common/Deprecated.hpp, dart/constraint/ConstraintSolver.hpp, dart/dynamics/BodyNode.hpp, dart/dynamics/Joint.hpp, dart/dynamics/Marker.hpp, dart/dynamics/MetaSkeleton.hpp, dart/dynamics/ReferentialSkeleton.hpp, dart/dynamics/Skeleton.hpp, dart/gui/SimWindow.hpp, dart/math/Geometry.hpp, dart/simulation/World.hpp, dart/utils/XmlHelpers.hpp, dart/utils/sdf/SdfParser.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/742)
=> Prepend DART_ to DEPRECATED and FORCEINLINE macros to avoid name conflicts

CHANGELOG.md, dart/collision/fcl/FCLCollisionDetector.cpp, dart/collision/fcl/FCLCollisionDetector.hpp, dart/collision/fcl/FCLCollisionObject.cpp, dart/collision/fcl/FCLCollisionObject.hpp, dart/collision/fcl/FCLTypes.hpp, dart/utils/XmlHelpers.cpp
FCL switched to use the smart pointers of the C++11 standard library since 0.5.0, and removed `XML_NO_ERROR` since 4.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/749)
=> Update API to support fcl 0.5 and tinyxml 4.0

CMakeLists.txt
We add unconditionally the SSE2 compiler flag when using GCC. This is making [non x86 arches to fail](https://buildd.debian.org/status/logs.php?pkg=kido&ver=0.1.0%2Bdfsg-1).
The bug report [comes from Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833817) and the developers made a couple of good points about it:
* SSE2 is enable by default if you run 64 bits on x86.
* We can not assume that i386 supports it since i386 for Debian implies 686 (or greater) and SSE2 was introduced in pentium4.
I think that the impact of removing it is really low.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/760)
=> Remove explicit SSE2 compiler flag

CMakeLists.txt, Changelog.md, appveyor.yml, cmake/FindFLANN.cmake, dart/collision/bullet/BulletCollisionNode.cpp, dart/collision/bullet/BulletCollisionNode.h, dart/config.h.in, data/skel/shapes.skel, unittests/CMakeLists.txt, unittests/testNearestNeighbor.cpp
This pull request switches to use `btConvexTriangleMeshShape` instead of `btGImpactMeshShape` for mesh shapes to support not only convex but also concave meshes.
Related issue: #762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/764)
=> Use btGImpactMeshShape instead of btConvexTriangleMeshShape

CHANGELOG.md, cmake/DARTFindDependencies.cmake, dart/config.hpp.in, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/URDFTypes.hpp, dart/utils/urdf/urdf_world_parser.hpp
`urdfdom_headers` 1.0 [is released](https://github.com/ros/urdfdom_headers/releases/tag/1.0.0) with API changes. The major change was replacing `boost` with C++11, which is a relatively small change.
This pull request adds support of `urdfdom_headers` 1.0 using different type aliasings depending on the `urdfdom_headers` versions.
This should fix [the build failures on Ubuntu `yakkety`](https://launchpadlibrarian.net/281296686/buildlog_ubuntu-yakkety-amd64.dart6_6.0.0-0~1541-daily~ubuntu16.10.1_BUILDING.txt.gz). 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/766)
=> Support urdfdom_headers 1.0

CHANGELOG.md, dart/collision/bullet/BulletCollisionDetector.cpp, dart/collision/fcl/FCLCollisionDetector.cpp, dart/dynamics/BoxShape.cpp, dart/dynamics/CapsuleShape.cpp, dart/dynamics/CapsuleShape.hpp, dart/dynamics/ConeShape.cpp, dart/dynamics/ConeShape.hpp, dart/dynamics/EllipsoidShape.cpp, dart/dynamics/LineSegmentShape.cpp, dart/dynamics/MeshShape.cpp, dart/dynamics/Shape.cpp, dart/dynamics/Shape.hpp, dart/dynamics/SoftMeshShape.cpp, dart/dynamics/SphereShape.cpp, dart/dynamics/detail/Shape.hpp, dart/gui/OpenGLRenderInterface.cpp, dart/gui/OpenGLRenderInterface.hpp, dart/gui/RenderInterface.cpp, dart/gui/RenderInterface.hpp, dart/gui/SimWindow.cpp, dart/gui/osg/ShapeFrameNode.cpp, dart/gui/osg/render/CapsuleShapeNode.cpp, dart/gui/osg/render/CapsuleShapeNode.hpp, dart/gui/osg/render/ConeShapeNode.cpp, dart/gui/osg/render/ConeShapeNode.hpp, dart/utils/SkelParser.cpp, data/skel/shapes.skel, data/skel/test/test_shapes.skel, unittests/testSkelParser.cpp
This pull request adds two new shape classes: `CapsuleShape` and `ConeShape`. Currently, only BulletCollisionDetector support the shapes. Both of OpenGL and OSG based renderers display the shapes. Also, these shapes can be parsed from SKEL file format. Here is part of an example skel file that contains the new shapes:
```xml
<visualization_shape>
<geometry>
<capsule>
<height>0.1</height>
<radius>0.05</radius>
</capsule>
</geometry>
</visualization_shape>
<visualization_shape>
<geometry>
<cone>
<height>0.1</height>
<radius>0.05</radius>
</cone>
</geometry>
</visualization_shape>
```
Additional changes: A syntactic sugar function `Shape::is<SHAPE_TYPE>()` is added that enables us to check the shape type from a `Shape` pointer in more convenient way. Here is a short example code:
```cpp
auto …
```
=> Add CapsuleShape and ConeShape

CHANGELOG.md, dart/collision/bullet/BulletCollisionDetector.cpp, dart/dynamics/MeshShape.cpp, dart/dynamics/MultiSphereShape.cpp, dart/dynamics/MultiSphereShape.hpp, dart/gui/SimWindow.cpp, dart/gui/osg/ShapeFrameNode.cpp, dart/gui/osg/render/MultiSphereShapeNode.cpp, dart/gui/osg/render/MultiSphereShapeNode.hpp, dart/utils/SkelParser.cpp, data/skel/shapes.skel, data/skel/test/test_shapes.skel, unittests/testSkelParser.cpp
This pull request adds new shape class `MultiSphereShape` inspired by `bullet`'s `btMultiSphereShape`. A multi-sphere shape is a convex hull of a collection of spheres.
Only BulletCollisionDetector support this shape. 
Both OpenGL and OSG merely draw the sub-spheres instead of the actual convex hull. This should be addressed in the future.
This shape is supported by SKEL file format. Here is part of an example skel file that for a `MultiSphereShape` with two sub-spheres:
```xml
<visualization_shape>
<transformation>0 0 0 0 0 0</transformation>
<geometry>
<multi_sphere>
<sphere>
<radius>0.05</radius>
<position>-0.075 0.0 0.0</position>
</sphere>
<sphere>
<radius>0.075</radius>
<position>0.075 0.0 0.0</position>
</sphere>
</multi_sphere>
</geometry>
<color>0.6 0.6 0.8</color> …
```
=> Add MultiSphereShape

dart/collision/fcl/FCLTypes.hpp
This is only a minuscule update. For compiling with fcl-0.5 needed to include <memory> from FCLTypes.hpp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/772)
=> Minor change: included <memory> from FCLTypes.hpp

CHANGELOG.md, dart/math/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/773)
=> Fix incorrect file search for math/detail headers

dart/dynamics/BoxShape.cpp, dart/dynamics/BoxShape.hpp, dart/dynamics/CapsuleShape.cpp, dart/dynamics/ConeShape.cpp, dart/dynamics/CylinderShape.cpp, dart/dynamics/CylinderShape.hpp, dart/dynamics/EllipsoidShape.cpp, dart/dynamics/EllipsoidShape.hpp, dart/dynamics/LineSegmentShape.cpp, dart/dynamics/LineSegmentShape.hpp, dart/dynamics/MeshShape.cpp, dart/dynamics/MeshShape.hpp, dart/dynamics/MultiSphereShape.cpp, dart/dynamics/MultiSphereShape.hpp, dart/dynamics/PlaneShape.cpp, dart/dynamics/PlaneShape.hpp, dart/dynamics/Shape.cpp, dart/dynamics/Shape.hpp, dart/dynamics/SoftMeshShape.cpp, dart/dynamics/SoftMeshShape.hpp, dart/dynamics/SphereShape.cpp, dart/dynamics/SphereShape.hpp
This pull request revives `Shape::getShapeType()` for backward compatibility that was malfunctioned in #769.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/779)
=> Revive Shape::getShapeType() for backward compatibility

CMakeLists.txt, Changelog.md, apps/addDeleteSkels/MyWindow.cpp, apps/atlasSimbicon/MyWindow.cpp, apps/bipedStand/MyWindow.cpp, apps/hybridDynamics/MyWindow.cpp, apps/jointConstraints/MyWindow.cpp, apps/mixedChain/MyWindow.cpp, apps/rigidCubes/MyWindow.cpp, apps/rigidShapes/MyWindow.cpp, apps/softBodies/MyWindow.cpp, apps/vehicle/MyWindow.cpp, dart/gui/GlutWindow.cpp, dart/gui/GlutWindow.h, dart/gui/SimWindow.cpp, dart/gui/SoftSimWindow.cpp, package.xml
SimWindow and the derived classes (e.g., `MyWindow` of apps) call `glutTimerFunc()` when resuming the simulation or replay. However, this leads to calling the callee function passes into `glutTimerFunc()` multiple times because `glutTimerFunc()` adds the callee function instead of resetting. I believe this is why the drawing rate was increased as reported by #729 and #792.
This PR fixes it by calling `glutTimerFunc()` once in `GlutWindow::initWindow()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/794)
=> Fix inconsistent frame rate of GlutWindow

CMakeLists.txt, Changelog.md, dart/collision/fcl/FCLTypes.h, dart/common/Deprecated.h, dart/config.h.in, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/URDFTypes.h, dart/utils/urdf/urdf_world_parser.h, package.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/799)
=> Support urdfdom_headers 1.0 for DART 5.1 (backport of #766)

dart/gui/Win3D.cpp
The non-osg display shows strange white lines with an nvidia driver.
The fix is based on this proposal
http://gamedev.stackexchange.com/questions/31941/opengl-behaviour-depending-on-the-graphics-card
that I found by googling around... I tested this with GTX1080 and NVidia
driver version 367.48 on debian linux. The strange white lines disappeared.
Compared to the rendering result as shown in issue #804, the new rendering is as espected. See:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/805)
=> fixed issue #804 - Rendering white lines with nvidia driver

tutorials/tutorialDominoes-Finished.cpp
I tried the tutorial with the dominoes but it did not work. I could never add
a new domino. There were three issues in the code.
a) The new domino was never added to the world.
b) The collision detection was always detecting a collision because
the new domino is in contact with the floor.
c) The tutorial description on the website is not related to
the code for the collision detection.
I fixed a) and b) and added some comments with this commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/807)
=> fixed tutorialDominoes-Finished - this did not work

.travis.yml, README.md, codecov.yml
Coveralls and Codecov are all promising coverage reporting services, but it seems [the layout of Codecov](https://codecov.io/gh/dartsim/dart/branch/codecov) looks more organized and intuitive to me comparing to [Coveralls'](https://coveralls.io/github/dartsim/dart?branch=master).
We could use Codecov with this minimal changes of this PR since they both work based on `gcov` but uploading to different services. There are some CMake scripts could be cleaned up, but I'd like to save it for future PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/806)
=> Use Codecov for online code coverage report

CHANGELOG.md, CMakeLists.txt, dart/constraint/ContactConstraint.cpp, dart/constraint/SoftContactConstraint.cpp, package.xml, unittests/unit/CMakeLists.txt, unittests/unit/test_ContactConstraint.cpp
`ContactConstraint` ignored the velocity of kinematic body nodes (body nodes with kinematic joints such as VELOCITY, ACCELERATION) in the relative contact velocity computation. This PR fixes the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/809)
=> Fix bug of ContactConstraint with kinematic joints

CMakeLists.txt
This is a complementary PR for #811 that fixes syntax error and improves messages for the case of that the target sources are empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/817)
=> Fix clang format setup

dart/gui/GlutWindow.cpp, dart/gui/MotionBlurSimWindow.cpp, dart/gui/MotionBlurSimWindow.hpp
1. Add Motion Blur to GUI by extending the SimWindow class, override only render() and displayTimer()
2. The Motion Blur class supports change of motion blur quality, in 0-5 scale, 0 means no motion blur, 5 means highest motion blur quality.
3. Only change needed to existing files are in line 86 of "GlutWindow.cpp"
From  glutInitDisplayMode(GLUT_DEPTH | GLUT_DOUBLE | GLUT_RGBA | GLUT_MULTISAMPLE);
To      glutInitDisplayMode(GLUT_DEPTH | GLUT_DOUBLE | GLUT_RGBA | GLUT_MULTISAMPLE | GLUT_ACCUM);
To enable Accumulated Buffer of GLUT
4. To test on existing examples, simply replace "class MyWindow : public dart::gui::SimWindow" with "class MyWindow : public dart::gui::MotionBlurSimWindow", in "MyWindow.cpp/hpp"
5. Code is written in a style similar to existing files in "dart/gui"
6. The …
=> Add  MotionBlurSimWindow  to GUI

dart/gui/Win3D.cpp
Smooth zooming and translation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/843)
=> relative zoom and translation with mouse

dart/utils/SkelParser.cpp
A quick bug fix for file:// URI in SkelParser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/847)
=> correct the right retriever in getRetriever function

dart/gui/osg/ShapeFrameNode.cpp, dart/gui/osg/ShapeFrameNode.hpp, dart/gui/osg/render/MeshShapeNode.cpp, dart/gui/osg/render/ShapeNode.cpp, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/DartLoader.hpp, data/urdf/test/issue838.urdf, examples/osgExamples/osgEmpty/osgEmpty.cpp, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue838.cpp
This pull request fixes the issues brought to light in issues #838 and #676. There are three specific bugs being fixed here:
1. urdfdom has some strange behavior where it treats the first entry in ``Link::visual_array`` differently from the rest with respect to its material information. If a material for a visual is defined globally in the urdf file, the first entry in ``Link::visual_array`` will be correctly linked to it, but none of the other entries will. This issue is discussed in more detail [here](https://github.com/dartsim/dart/issues/838#issuecomment-284209519). This pull request fixes the issue on DART's end with a bit of post-processing.
2. When the ``MeshShape::mScale`` is anything other than Eigen::Vector3d::One(), the normal vectors that are used in the OSG extension also get …
=> Fixes for Issues #838 and #676

dart/gui/OpenGLRenderInterface.cpp, dart/gui/OpenGLRenderInterface.hpp, dart/gui/RenderInterface.cpp, dart/gui/RenderInterface.hpp, dart/gui/SimWindow.cpp
Previously, DART only draws the spheres in a `MultiSphereShape` while the actual shape is the convex hull enclosing all the spheres. This PR still doesn't render the convex hull but improves the visualization by drawing the cylinders that connect the pairs of the spheres.
Before:
After:
=> Improve MultiSphereShape rendering

dart/collision/bullet/BulletCollisionDetector.cpp, dart/dynamics/CMakeLists.txt, dart/dynamics/MultiSphereConvexHullShape.cpp, dart/dynamics/MultiSphereConvexHullShape.hpp, dart/dynamics/MultiSphereShape.hpp, dart/gui/SimWindow.cpp, dart/gui/osg/ShapeFrameNode.cpp, dart/gui/osg/render/MultiSphereShapeNode.cpp, dart/gui/osg/render/MultiSphereShapeNode.hpp, dart/utils/SkelParser.cpp, unittests/unit/test_SkelParser.cpp
This PR renames `MultiSphereShape` to `MultiSphereConvexHullShape` as suggested in this [comment](https://github.com/dartsim/dart/pull/862#issuecomment-290128731).
=> Rename MultiSphereShape to MultiSphereConvexHullShape

dart/common/detail/Cloneable.hpp
If DART is built with C++14 enabled, `dart::common::make_unique()` conflicts with `std::make_unique` (introduced in C++14). This PR adds the full namespace where it's missing to avoid the confliction.
=> Use make_unique with full namespace

CMakeLists.txt, dart/dynamics/MetaSkeleton.hpp, dart/dynamics/ReferentialSkeleton.cpp, dart/dynamics/ReferentialSkeleton.hpp, dart/dynamics/Skeleton.cpp, dart/dynamics/Skeleton.hpp, unittests/comprehensive/test_Skeleton.cpp
The newly added APIs are just syntactic sugar to get the joints and body nodes with a name. Probably, some of the implementation are not that efficient.
=> Add getters for joints/bodies to MetaSkeleton

dart/utils/SkelParser.cpp, dart/utils/urdf/DartLoader.cpp, unittests/unit/test_DartLoader.cpp
This PR fixes the URDF parser to read joint friction.
Resolves #890.
=> Read joint friction from URDF

dart/utils/sdf/SdfParser.cpp
While working on a Gazebo plugin that uses DART, I noticed that `SdfParser::readSekeleton` incorrectly loads sdf models that have the `<use_parent_model_frame>` tag enabled. The problem is that the parser applies an isometry to joint axes marked with the tag while only a rotation should be applied. This PR modifies `SdfParser::readAxisElement` to only use the rotational component of the isometry.
=> SdfParser <use_parent_model_frame> tag

.travis.yml, dart/collision/CollisionFilter.cpp, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue895.cpp
I noticed that if I create multiple collision objects for a single link in Gazebo while using DART physics, they are collision checked against each other even though they are part of the same link (body node). The proposed change to `CollisionFilter::needCollision` prevents collision checking between shapes attached to the same body node.
See [collisions.world](https://github.com/dartsim/dart/files/1163781/collisions.world.txt) for an example in Gazebo. It contains a model with two links and self-collisions enabled. The top link consists of two flush collision meshes. Without the change, contacts points (blue dots) are detected between the flush meshes.
With the change, no such contacts are detected.
=> Avoid collision checking between objects from the same body node

dart/gui/osg/CMakeLists.txt
This PR has two related (but independent) purposes:
1. Prevent `dart-gui-osg` from being built when OSG is not detected. ~~This is done by wrapping the second half of `dart/gui/osg/CMakeLists.txt` in an if-block.~~ This is done by returning immediately if OpenSceneGraph cmake variables cannot be found. This was not needed in the past because the call to `add_subdirectory(osg)` used to be wrapped in an if-statement.
2. More rigorously check whether OSG exists. In the process of fixing this, I discovered that the version of `FindOpenSceneGraph.cmake` that is provided with `cmake-3.5` will set `OPENSCENEGRAPH_FOUND` to true if it finds libopen**threads**, even if libopen**scenegraph** isn't actually installed. I believe this is a bug on the part of either CMake or OpenSceneGraph, because …
=> Protect dart-gui-osg and check more rigorously for the presence of OSG

dart/gui/osg/CMakeLists.txt
Same as #898 but targeting release-6.2 branch.
=> (6.2) Protect dart-gui-osg and check more rigorously for the presence of OSG

dart/constraint/WeldJointConstraint.cpp, dart/constraint/WeldJointConstraint.hpp
I couldn't find any reason to restrict access to setting mRelativeTransform. I also couldn't identify any other data members who would be impacted by changing mRelativeTransform, so the setter is just a straightforward copy.
This addresses #903.
=> Adding setter and getter for WeldJointConstraint::mRelativeTransform

LICENSE
This PR slightly changes the format of `LICENSE` file to enable Github to detect it correctly.
=> Reformat LICENSE to be detected by Github

dart/collision/CollisionFilter.cpp, dart/collision/CollisionFilter.hpp, dart/collision/bullet/BulletCollisionDetector.cpp, dart/collision/bullet/detail/BulletCollisionDispatcher.cpp, dart/collision/bullet/detail/BulletOverlapFilterCallback.cpp, dart/collision/dart/DARTCollisionDetector.cpp, dart/collision/detail/UnorderedPairs.hpp, dart/collision/fcl/FCLCollisionDetector.cpp, dart/collision/ode/OdeCollisionDetector.cpp, dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.hpp, unittests/comprehensive/test_Collision.cpp
This pull request enables us to enable/disable collision checking for specific pairs of body nodes by maintaining a blacklist in `BodyNodeCollisionFilter`. Also, `ConstraintSolver::getCollisionOption()` is added to enable to modify the collision filter through it as:
```cpp
auto collisionOption = world->getConstraintSolver()->getCollisionOption();
auto collisionFilter = collisionOption.getCollisionFilter();
collisionFilter->addBodyNodePairToBlackList(body0, body1);
```
Minor changes:
* Add `CompositeCollisionFilter` class to enable to use more than two collision filters by composing them in this class
* Rename `CollisionFilter::needCollision(...)` to `CollisionFilter::needsCollisionCheck(...)`
=> Add blacklist to BodyNodeCollisionFilter

dart/common/Factory.hpp, dart/common/detail/Factory-impl.hpp
We're planning to another python binding package for DART, namely dartpy, that uses chimera to automatically generate the bindings. Unfortunately, chimera has an [issue of using lambda function parameter in a variadic template class](https://github.com/personalrobotics/chimera/issues/148). This PR workaround the issue by replacing the lambda function with a static member function.
=> Chimera friendly version

ci/install_osx.sh
I haven't figured out the actual reason, but it seems tapping `dartsim/dart` isn't working and it causes the CI test failure on macOC. This PR changes the script to install `fcl` using its full formula path so that it doesn't require tapping.
***
=> Install fcl using the full formulae name

CHANGELOG.md, unittests/comprehensive/test_Collision.cpp, unittests/comprehensive/test_Frames.cpp, unittests/comprehensive/test_Skeleton.cpp, unittests/unit/test_ContactConstraint.cpp
GCC 7.2.0 prints warnings of `-Wdangling-else`. It seems this is because if-statements with a single line macro is prone to dangling else. This PR suppresses these warnings by adding explicit braces around the single line of the macro.
***
=> Suppress -Wdangling-else warnings

dart/dynamics/MeshShape.cpp
This is a fix to #734. In short:
- There's a small bug in `setScale` method of `MeshShape`; i.e., `_updateBoundingBoxDim` needs to be called before `updateVolume`
- The calls to `updateVolume` and `_updateBoundingBoxDim` in the `setMesh` method are not needed.
=> Fix for #734

CHANGELOG.md, dart/dynamics/ArrowShape.cpp, dart/dynamics/BoxShape.cpp, dart/dynamics/BoxShape.hpp, dart/dynamics/CapsuleShape.cpp, dart/dynamics/CapsuleShape.hpp, dart/dynamics/ConeShape.cpp, dart/dynamics/ConeShape.hpp, dart/dynamics/CylinderShape.cpp, dart/dynamics/CylinderShape.hpp, dart/dynamics/EllipsoidShape.cpp, dart/dynamics/EllipsoidShape.hpp, dart/dynamics/LineSegmentShape.cpp, dart/dynamics/LineSegmentShape.hpp, dart/dynamics/MeshShape.cpp, dart/dynamics/MeshShape.hpp, dart/dynamics/MultiSphereConvexHullShape.cpp, dart/dynamics/MultiSphereConvexHullShape.hpp, dart/dynamics/PlaneShape.cpp, dart/dynamics/PlaneShape.hpp, dart/dynamics/Shape.cpp, dart/dynamics/Shape.hpp, dart/dynamics/SoftMeshShape.cpp, dart/dynamics/SoftMeshShape.hpp, dart/dynamics/SphereShape.cpp, dart/dynamics/SphereShape.hpp
=> Lazy evaluation for shape volume and bounding-box

CHANGELOG.md, dart/simulation/World.cpp, dart/simulation/World.hpp, dart/utils/SkelParser.cpp, dart/utils/sdf/SdfParser.cpp, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/urdf_world_parser.cpp, examples/atlasSimbicon/Main.cpp, examples/osgExamples/osgAtlasPuppet/osgAtlasPuppet.cpp, tutorials/tutorialMultiPendulum-Finished/tutorialMultiPendulum-Finished.cpp, tutorials/tutorialMultiPendulum/tutorialMultiPendulum.cpp, unittests/comprehensive/test_Building.cpp, unittests/comprehensive/test_Constraint.cpp, unittests/comprehensive/test_Joints.cpp, unittests/comprehensive/test_World.cpp, unittests/unit/test_VskParser.cpp
=> Add World::create()

CHANGELOG.md, dart/common/detail/CompositeData.hpp
Same as #963, but targeting `release-6.4`
=> Port clang warning fix over to 6.4

dart/common/detail/CompositeData.hpp
This fixes issue #954 in which clang-5.0 emits a warning about a typename being interpreted as a constructor in certain contexts.
***
***
Do we care about the changelog for a warning fix like this? It doesn't have any effect on API, ABI, or behavior.
=> Use template specialization to sidestep complaints from clang

README.md
Happy to announce that DART has been accepted to [JOSS](http://joss.theoj.org/)!  :tada: 
Here is the paper webpage: [![DOI](http://joss.theoj.org/papers/10.21105/joss.00500/status.svg)](https://doi.org/10.21105/joss.00500)
This PR adds the JOSS Paper badge to `README.md`.
=> JOSS Paper

CONTRIBUTING.md
This PR adds the style guide documentation ported from [AIKIDO's style guide](https://github.com/personalrobotics/aikido/blob/f09ef8476f2aac45c89726aef46cbb881f2840e4/STYLE.md) that is initially created by @psigen and improved by the AIKIDO development team.
This is not complete, but it would be good to start to maintain the style guide document for the contributors to DART (and ourselves :smile:).
***
=> Add style guide documentation

CHANGELOG.md, dart/dynamics/BodyNode.cpp, dart/dynamics/BodyNode.hpp, dart/dynamics/detail/BodyNode.hpp, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue986.cpp, unittests/regression/test_IssueXXX.cpp
GCC 7.2.0/Clang Apple LLVM 9.0.0 fail to build `createShapeNode()` with errors as follows:
```
BodyNode.hpp:149:16: error: ‘class std::shared_ptr<dart::dynamics::SphereShape>’ has no member named ‘mName’
properties.mName = getName()+"_ShapeNode_"
```
Travis also reports the [same error](https://travis-ci.org/dartsim/dart/jobs/341632273#L2118-L2120).
=> Extend createShapeNode to accept more types of arguments

CHANGELOG.md, dart/dynamics/MetaSkeleton.hpp, dart/dynamics/ReferentialSkeleton.cpp, dart/dynamics/ReferentialSkeleton.hpp, dart/dynamics/Skeleton.cpp, dart/dynamics/Skeleton.hpp, unittests/comprehensive/test_Skeleton.cpp
=> Add hasBodyNode() and hasJoint() to MetaSkeleton

CHANGELOG.md, dart/common/Console.hpp
to avoid namespace conflicts
***
=> Use global namespace resolution in macro

CHANGELOG.md, CMakeLists.txt, package.xml
This updates the package.xml to (I think) more closely adhere to the documentation [here](http://wiki.ros.org/catkin/package.xml). If anyone has more experience writing package.xml files, please critique this.
I named myself as the maintainer so that if ROS users/maintainers have issues with the package, they'll direct issues to me first. I'll go ahead and take responsibility for that, since I'm surrounded by coworkers who are experts at ROS package management.
I'm not totally clear on whether it would be better to put this in 6.3 or 6.4. I'm thinking we can do a 6.3.1 release after merging this and make that the first DART release into ROS. If anyone dislikes that idea, please do say something, since I'm new to this process.
=> Update package.xml based on catkin documentation

CHANGELOG.md, package.xml
After running some experiments with the ROS release tools, it seems they expect the package name for fcl to be `libfcl-dev`, and `libccd` doesn't seem to be recognized as a package (but we only depend on it transitively through `libfcl`, so it shouldn't matter).
This version of the package.xml seemed to work with `bloom-release`.
=> Fixing package name of FCL and removing libccd in package.xml

CHANGELOG.md, package.xml
Since DART does not depend on catkin in order to configure and build, we can specify that it's build type is cmake instead of catkin. This prevents catkin from complaining about the project not being a catkin package.
This brings us back to conforming to REP-136, which I had naively erased, since I wasn't aware of the nuances between a "catkin package" and a "third-party package" (dartsim is considered the latter).
This also adds a boost dependency that was missing.
=> More fixes for package.xml

CHANGELOG.md, package.xml
It turns out that the recommendations of REP-136 are only using terminology for format 1 of package.xml, but we want to use format 2. This change should accommodate both needs.
=> Conform to package.xml format 2

CHANGELOG.md, dart/gui/osg/CMakeLists.txt
Sorry for all the PR spam, but we're almost there! The last thing the ROS package build farm is complaining about is a cmake warning that we expect to occur. This results in an "unstable" status, which is acceptable, but I'd prefer we make it stable since it's such an easy fix (and this should probably be a status message instead of a warning anyway).
I also updated the changelog to include PR #1032 which I accidentally skipped.
=> Final step to give dartsim stable status in ROS build farm

CHANGELOG.md, CMakeLists.txt
This has been causing trouble in the ROS Build Farm, because the build farm passes the argument `-DCMAKE_BUILD_TYPE=None` to cmake.
I think in general we should consider a redesign (mostly a simplification) of how we handle build types, but I'll open a separate issue for that.
=> Avoid using an undefined cmake macro/function "build_error"

CMakeLists.txt
DART used to exclude examples and tutorials from `all` target, but they are accidentally added back to `all` target by #1015. This PR fixes it by adding `EXCLUDE_FROM_ALL` option to `add_subdirectory` for examples and tutorials.
***
=> Exclude examples and tutorials from all target

CHANGELOG.md, dart/gui/osg/Viewer.cpp, dart/gui/osg/Viewer.hpp
=> Add FOV API to OSG viewer

CHANGELOG.md, dart/simulation/World.cpp, dart/simulation/World.hpp, unittests/comprehensive/test_World.cpp
`World::hasSkeleton` takes `Skeleton` as a shared pointer since `Skeleton` is enforced to be created as a shared pointer by calling `Skeleton::create()`.
***
=> Add World::hasSkeleton()

CHANGELOG.md, dart/dynamics/AssimpInputResourceAdaptor.cpp, dart/dynamics/MeshShape.cpp
This PR fixes the memory leaks reported in #1063.
***
=> Fix memory leaks in mesh loading

CHANGELOG.md, dart/common/Memory.hpp
**Summary**
* Include #1057 into 6.5.0 instead of 6.4.1 (decided not to release 6.4.1)
* Update changelog
**PPA builds**
* [trusty](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/14872022)
* [xenial](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/14872024)
* [bionic](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+build/14872014)
=> Packaging 6.5.0

dart/collision/bullet/BulletCollisionDetector.cpp
This may not be problematic if we include the system include directory (e.g., `/usr/include/`) since bullet is usually installed under the directory, but this wouldn't work otherwise.
=> Fix incorrect bullet header inclusion

CHANGELOG.md, dart/dynamics/VoxelGridShape.cpp, dart/dynamics/VoxelGridShape.hpp
This PR adds more occupancy update functions that can specify reference frame of the sensor origin and the point cloud.
***
=> Add more occupancy update functions to VoxelGridShape

CHANGELOG.md, dart/utils/DartResourceRetriever.cpp, dart/utils/DartResourceRetriever.hpp
This PR adds a fallback option to `DartResourceRetriever` to use an environment variable to search DART data files. The existing preprocessor, `DART_DATA_GLOBAL_PATH`, doesn't work if the package manager uses temporary install directory (e.g., Launchpad PPA and Homebrew).
This should resolve #1091 and https://github.com/dartsim/homebrew-dart/issues/54.
***
=> Add option to DartResourceRetriever to search from environment variable DART_DATA_PATH

CHANGELOG.md, CMakeLists.txt, dart/utils/DartResourceRetriever.cpp, package.xml
=> Fix checking file existence in DartResourceRetriever

dart/CMakeLists.txt
**Duplicate of #1115 (rebased on release-6.7)**
In a clean (X)Ubuntu 18.04 installation, when compiling with SIMD option (native flags) and gcc (version=7.3.0) or clang (version=6.0.0), some tests (and examples) fail because of segfaults.
The flag -faligned-new solves the issue (alternatively, one could enable C++17, but this flag enables just the right feature for the job). I do not know (and I cannot test) what happens for Visual Studio, so I left it untouched.
Let me know if you can reproduce the error and if there's another way of making it work.
=> Fix for aligned in newer gcc?

dart/common/AspectWithVersion.hpp, dart/common/detail/AspectWithVersion.hpp
The default constructors of `AspectWith[StateAnd]VersionedProperties` are deleted, but the other constructors of them actually allow to create them without parameters because of their default parameter values. This leads to a compilation error of an ambiguous function call when creating them without parameters. This PR removes the delete declarations of the default constructors.
=> Remove deleted default constructors of AspectWith[StateAnd]VersionedProperties

Brewfile
Building with `pagmo` solver increases the build time that leads to time out for Travis CI's maximum build time (fails all the time because of this). So this PR disables it.
It'd be great to test all the components of DART, but it also has no point if it fails all the time due to the exceeding build time limit.
=> Disable build with pagmo on macOS

dart/CMakeLists.txt
Coming back to #1116, because it seems that in some older versions of gcc (e.g., I have 5.4 in my second computer) we get `unrecognized command line argument '-faligned-new'`. This should activate the argument only when required (and doesn't break the compilation). In clang compilers I did not notice the same (I tested with clang 4.0)..
=> Fix aligned for old gcc compilers

CMakeLists.txt
This fixes CMake warning (>= 3.11):
```
CMake Warning (dev) at /usr/local/share/cmake-3.12/Modules/FindOpenGL.cmake:270 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
compatibility with CMake 3.10 and below the legacy GL library will be used.
```
by specifying CMP0072 policy.
***
**Before merging a …
=> Fix CMake warning when CMP0072 is not set

examples/humanJointLimits/InSourceBuild.cmake
A quick fix of CMake syntax error introduced in #1207.
***
=> Fix cmake syntax mistake

cmake/Components.cmake, cmake/DARTFindurdfdom.cmake, cmake/DARTMacros.cmake, dart/utils/urdf/CMakeLists.txt, examples/humanJointLimits/InSourceBuild.cmake
Currently, the transitive dependencies of DART are propagated by using CMake variables. For example, all the dependency libraries are stored in `DART_LIBRARIES`, which will be defined by loading `DARTConfig.cmake` through calling `find_package(DART)` in a downstream project. 
However, this approach can fail to load the dependency. The items in `DART_LIBRARIES` can be either of the path to a library file or a target. Path items work fine (as long as the path is correct), but not targets because the downstream project don't know how to import the target only from the target name. This PR fixes it by letting `DARTConfig.cmake` loading the dependency targets by calling `find_packages()` for them. This approach should work as long as all the upstream dependencies loading relevant targets …
=> Import dependency targets when loading DARTConfig.cmake

.ci/install_linux.sh, .ci/script.sh, .clang-format, .travis.yml, CMakeLists.txt, dart/common/detail/LockableReference-impl.hpp, dart/constraint/BoxedLcpConstraintSolver.cpp, dart/constraint/ContactConstraint.cpp, dart/dynamics/detail/TranslationalJoint2DAspect.hpp, dart/math/detail/Random-impl.hpp, dart/optimizer/Population.cpp, examples/osgExamples/osgBoxStacking/osgBoxStacking.cpp
We use a specific version of ClangFormat because different version can format the code differently even with the same configuration. In this PR, we update the ClangFormat version to 6.0. I particularly chose 6.0 because it's the highest version that is available on the Ubuntu distros we support for DART >= 6.8.
***
=> Update ClangFormat to version 6.0

CHANGELOG.md, cmake/DARTFindEigen3.cmake, cmake/DARTFindGLUT.cmake, cmake/DARTFindIPOPT.cmake, cmake/DARTFindNLOPT.cmake, cmake/DARTFindODE.cmake, cmake/DARTFindOpenGL.cmake, cmake/DARTFindassimp.cmake, cmake/DARTFindccd.cmake, cmake/DARTFindfcl.cmake, cmake/DARTFindflann.cmake, cmake/DARTFindoctomap.cmake, cmake/DARTFindpagmo.cmake, cmake/DARTFindtinyxml2.cmake, cmake/DARTFindurdfdom.cmake
There could be a case that `find_package()` is module mode when we intend it to be config mode (by not providing own module file) if the downstream package provides a module file. This PR specifies the mode explicitly to avoid this confusion.
***
=> Specify mode for find_package()

unittests/comprehensive/test_Dynamics.cpp
This is a try to fix #1211 by decreasing the input impulses.
***
=> Lower impulses of DynamicsTest.testImpulseBasedDynamics

unittests/regression/CMakeLists.txt, unittests/regression/test_Issue1234.cpp
This PR is only for illustrative purposes. We can go ahead and decline it whenever. I just wanted to present a test that illustrates the findings that I reported in #1234.
I've noticed that the ODE collision detector can have totally inconsistent results in between tests, and the results also seem to be very sensitive to the order in which the tests are run (e.g. if you change the order of the some of the elements in the for-loops, the results can be dramatically different). This makes me suspect that there's some very serious undefined behavior occurring, either in our ODE wrapper or in ODE itself.
=> Unreliable plane-mesh collision detection

CHANGELOG.md, dart/external/odelcpsolver/lcp.cpp
A line in the LCP solver may print out excessive warnings over minor imprecision. This causes unnecessary terminal spam that looks like this:
```
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP …
```
=>  Make the LCP internal error printout less aggressive

CHANGELOG.md, CMakeLists.txt
The change uses `GNUInstallDirs` cmake module to provide platform specific paths. Not sure how this can affect how Dart manages the directory structure on Windows.
Replaces #1239
=> Use GNUInstallDirs for lib/include path

CHANGELOG.md, CMakeLists.txt, dart/common/detail/Cloneable.hpp, dart/common/detail/ProxyAspect.hpp, package.xml, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue1243.cpp
Same as #1244 but targeting release-6.7 for a patch release.
=> Patch for issue #1243 and add a regression test

.ci/script.sh, cmake/CodeCoverage.cmake
Travis build with Codcov reporting fails due to huge log files.
This PR is borrowed from:
* https://github.com/personalrobotics/aikido/pull/489
* https://github.com/personalrobotics/aikido/pull/495
* https://github.com/personalrobotics/aikido/pull/501
=> Silence gcov output

CHANGELOG.md, cmake/DARTFindBoost.cmake
This allows us to use the boost targets even when the default `FindBoost.cmake` doesn't define imported boost targets.
***
=> Fix not defining boost targets

.azure-pipelines.yml, .travis.yml
The CI test of debug mode + codecov on Travis fails due to Travis's time limit (50 min).
This PR changes the CI settings to only test release builds on Travis CI, and let Azure test debug builds and others that require long build time (e.g., codecov report and dartpy build).
=> Offload debug build tests on Travis CI to Azure

CHANGELOG.md, dart/dynamics/Inertia.cpp, dart/math/detail/Random-impl.hpp, unittests/unit/CMakeLists.txt, unittests/unit/test_Inertia.cpp
[The last check of `Inertia::verifySpatialTensor()`](https://github.com/dartsim/dart/blame/a94c9d09938c3cc5f6a463d6e8747d6a78357b15/dart/dynamics/Inertia.cpp#L352-L375) doesn't correctly test the transpose relationship of the top-right block and the bottom-left block.
Resolves #1257 
***
=> Fix incorrect transpose check in Inertia::verifySpatialTensor()

CHANGELOG.md, dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.hpp, dart/simulation/World.cpp, dart/simulation/World.hpp, unittests/comprehensive/test_World.cpp
`World::setConstraint()` doesn't copy constraints.
Introduce `ConstraintSolver::setFromOtherConstraintSolver()` to properly copy skeletons and contraints from existing constraint solver. This is to let `ConstraintSolver` handle the copy instead of the caller (e.g., `World`).
***
=> Fix not copying constraints in setting new constraint solver

dart/gui/osg/CMakeLists.txt
OSG installs its binaries in `<install_prefix>/lib<arch>`, which is not searchable by CMake < 3.12.
Explicily set CMake to find lib64 paths by setting `FIND_LIBRARY_USE_LIB64_PATHS` as `TRUE` as suggestted [here](https://github.com/openscenegraph/OpenSceneGraph/pull/660#issuecomment-441502412).
This is tangential to #1262.
***
=> Fix finding manually installed OpenSceneGraph for CMake < 3.12

.azure-pipelines.yml
Per https://github.com/Microsoft/azure-pipelines-image-generation/pull/732, Azure uses Boost 1.69 by default, it seems there is no option for choosing the system boost (1.58). For some reason, [DART fails to build with Boost 1.69](https://dev.azure.com/dartsim/dart/_build/results?buildId=492), which should be fixed. In any case, the Xenial build should use the system Boost, so this PR changes to use docker for Xenial build.
=> Use docker for Xenial build on Azure

CHANGELOG.md, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/DartLoader.hpp, unittests/unit/test_DartLoader.cpp
This PR addresses https://github.com/dartsim/dart/issues/1267.
***
=> Change urdf parser to warn if robot model has multi-tree

CHANGELOG.md, dart/collision/CollisionDetector.hpp, dart/collision/bullet/BulletCollisionDetector.cpp, dart/collision/bullet/BulletCollisionDetector.hpp, dart/collision/dart/DARTCollisionDetector.cpp, dart/collision/dart/DARTCollisionDetector.hpp, dart/collision/fcl/FCLCollisionDetector.cpp, dart/collision/fcl/FCLCollisionDetector.hpp, dart/collision/ode/OdeCollisionDetector.cpp, dart/collision/ode/OdeCollisionDetector.hpp, dart/constraint/BoxedLcpConstraintSolver.cpp, dart/constraint/BoxedLcpConstraintSolver.hpp, dart/constraint/BoxedLcpSolver.hpp, dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.hpp, dart/constraint/DantzigBoxedLcpSolver.cpp, dart/constraint/DantzigBoxedLcpSolver.hpp, dart/constraint/PgsBoxedLcpSolver.cpp, dart/constraint/PgsBoxedLcpSolver.hpp, dart/external/odelcpsolver/lcp.cpp, dart/external/odelcpsolver/lcp.h, dart/simulation/World.cpp, dart/simulation/World.hpp, examples/osgExamples/osgBoxStacking/osgBoxStacking.cpp, unittests/comprehensive/test_World.cpp, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue892.cpp, unittests/unit/test_ContactConstraint.cpp
Dantzig LCP solver sometimes returns inaccurate solution or even NAN values when the LCP doesn't have a solution. More importantly, `BoxedLCPConstraintSolver` uses the solution without any sanity checks, which easily leads to unstable simulation. This is reported in #892.
Let `BoxedLCPConstraintSolver` to use more robust LCP solver such as PGS when it fails to solve with the primary LCP solver. In addition to that, as a final resort, it discards NAN value solution when the secondary LCP solver failed as well.
Added the regression test provided by @pchorak. Thanks!
***
=> Allow BoxedLcpConstraintSolver to have secondary LCP solver

CHANGELOG.md, dart/dynamics/Chain.cpp, dart/dynamics/Chain.hpp, dart/dynamics/Linkage.cpp, dart/dynamics/Linkage.hpp, unittests/comprehensive/test_MetaSkeleton.cpp
No convenient way to create a sequence Linkage.
Add an utility constructor to `Linkage::Criteria` to create a sequence Linkage:
```cpp
Criteria(BodyNode* start, BodyNode* target, bool includeBoth = false);
```
* Resolve #1268 
***
=> Add a new Criteria constructor for creating sequence

CHANGELOG.md, dart/dynamics/HierarchicalIK.cpp, dart/dynamics/HierarchicalIK.hpp, dart/dynamics/InverseKinematics.cpp, dart/dynamics/InverseKinematics.hpp, dart/gui/osg/DragAndDrop.cpp, examples/osgExamples/osgAtlasPuppet/osgAtlasPuppet.cpp, examples/osgExamples/osgHuboPuppet/osgHuboPuppet.cpp, examples/osgExamples/osgWamIkFast/WamWorld.cpp, unittests/comprehensive/CMakeLists.txt, unittests/comprehensive/test_InverseKinematics.cpp, unittests/unit/test_Optimizer.cpp
IK solvers apply solution even when the solver failed to solve.
Apply solution only on success.
Added a simple unit test that checks if IK solver changes joint values when the solver failed.
***
=> Apply IK solution only when the solver succeeded

CHANGELOG.md, dart/gui/osg/CMakeLists.txt, dart/gui/osg/GridVisual.cpp, dart/gui/osg/GridVisual.hpp, examples/osgExamples/osgPointCloud/main.cpp
This PR adds grid visual object to the OSG renderer. The grid can be configurable in terms of plane type (xy/yz/zx), offset, line count, line step size, minor lines per major line, line width, and line color.
***
=> Add grid visual to OSG renderer

CHANGELOG.md, cmake/DARTFindDependencies.cmake
For some unknow reasons, Homebrew FCL package + octomap fails in collision checking for octomap. This PR disable octomap support only macOS for now.
***
=> Disable octomap support on macOS

dart/simulation/World.hpp
State copy on skeleton clone was resolved by https://github.com/dartsim/dart/pull/691. Thanks to @brianhou for finding this.
***
=> Remove outdated code in World.hpp

CHANGELOG.md, dart/constraint/BoxedLcpConstraintSolver.hpp
Fixes #1288 by adding default values to solver arguments.
=> BoxedLcpConstraintSolver: API compatible with 6.7

CHANGELOG.md, dart/collision/fcl/BackwardCompatibility.hpp
This PR fixes #1290 by treating `FCL_HAVE_OCTOMAP` as boolean instead of checking whether it's defined.
***
=> Fix building with FCL built without Octomap

.appveyor.yml
It will be enabled once Appveyor installs CMake >= 3.14 on the container.
Related issue: https://github.com/dartsim/dart/issues/1180
=> Disable building on Appveyor until CMake >= 3.14 installed

CHANGELOG.md, dart/dynamics/PointCloudShape.cpp, dart/dynamics/PointCloudShape.hpp, dart/dynamics/VoxelGridShape.cpp, dart/dynamics/VoxelGridShape.hpp, dart/gui/osg/render/PointCloudShapeNode.cpp, dart/gui/osg/render/PointCloudShapeNode.hpp, dart/gui/osg/render/VoxelGridShapeNode.cpp, dart/gui/osg/render/VoxelGridShapeNode.hpp, examples/osgExamples/osgPointCloud/main.cpp
=> Improve voxel grid and point cloud rendering performance

CHANGELOG.md, CMakeLists.txt, dart/external/imgui/CMakeLists.txt, dart/gui/osg/ImGuiHandler.cpp, dart/gui/osg/ImGuiViewer.cpp, dart/gui/osg/ImGuiViewer.hpp, examples/osgExamples/osgAtlasSimbicon/AtlasSimbiconWidget.cpp, examples/osgExamples/osgAtlasSimbicon/AtlasSimbiconWidget.hpp, examples/osgExamples/osgAtlasSimbicon/main.cpp, examples/osgExamples/osgBoxStacking/osgBoxStacking.cpp, examples/osgExamples/osgImGui/osgImGui.cpp, examples/osgExamples/osgPointCloud/main.cpp, examples/osgExamples/osgTinkertoy/TinkertoyWidget.cpp, examples/osgExamples/osgTinkertoy/TinkertoyWidget.hpp, examples/osgExamples/osgTinkertoy/main.cpp, package.xml
=> Fix crashing on exiting OSG + ImGui applications

CHANGELOG.md, dart/collision/CMakeLists.txt, dart/collision/CollisionDetector.cpp, dart/collision/CollisionDetector.hpp, dart/collision/RaycastOption.cpp, dart/collision/RaycastOption.hpp, dart/collision/RaycastResult.cpp, dart/collision/RaycastResult.hpp, dart/collision/bullet/BulletCollisionDetector.cpp, dart/collision/bullet/BulletCollisionDetector.hpp, unittests/comprehensive/CMakeLists.txt, unittests/comprehensive/test_Raycast.cpp
=> Add raycast query to BulletCollisionDetector

CHANGELOG.md, dart/gui/osg/WorldNode.cpp, dart/gui/osg/WorldNode.hpp, examples/atlas_simbicon/AtlasSimbiconEventHandler.hpp, examples/atlas_simbicon/AtlasSimbiconWidget.cpp, examples/atlas_simbicon/AtlasSimbiconWidget.hpp, examples/atlas_simbicon/AtlasSimbiconWorldNode.cpp, examples/atlas_simbicon/AtlasSimbiconWorldNode.hpp, examples/atlas_simbicon/main.cpp
The incompatibility issue of ImGuiViewer + OSG shadow found in https://github.com/dartsim/dart/pull/978 was fixed in https://github.com/dartsim/dart/pull/1274. Particularly, these two blocks ([1](https://github.com/dartsim/dart/blob/731267caef5abf8651f663be2adb974b17735392/dart/external/imgui/imgui_impl_opengl2.cpp#L100-L106), [2](https://github.com/dartsim/dart/blob/731267caef5abf8651f663be2adb974b17735392/dart/external/imgui/imgui_impl_opengl2.cpp#L182-L188)) resolved the issue.
***
=> Remove warning of ImGuiViewer + OSG shadow

CHANGELOG.md, codecov.yml, dart/gui/osg/ShapeFrameNode.cpp, dart/gui/osg/ShapeFrameNode.hpp, dart/gui/osg/WorldNode.cpp, dart/gui/osg/WorldNode.hpp
~~In `clearUnusedNodes()`, if an unused node doesn't have any holders that have the ownership, it becomes dangling pointers since `WorldNode` holds nodes as raw pointers.~~
In `clearUnusedNodes()`, an unused node is possible to hold a dangling pointer to `ShapeFrame`. This can happen because `ShapeFrameNode` doesn't have the ownership of `ShapeFrame`. This leads to dereferencing a dangling pointer in the logic of checking whether the node is shadowed or not. 
This PR changes the behavior of the node deletion logic to remove the access to the internal `ShapeFrame` pointer. Instead, it now unconditionally removes the node from both of shadowed group and unshadowed group. I believe this is safe because OSG will ignore the attempt of removing a non-existing node in the group.
***
**Before …
=> Fix dereferencing a dangling pointer in WorldNode

CHANGELOG.md, dart/dynamics/MeshShape.cpp
=> Add safeguard for accessing Assimp color

CHANGELOG.md, dart/dynamics/PointCloudShape.cpp, dart/dynamics/PointCloudShape.hpp, dart/gui/osg/render/PointCloudShapeNode.cpp, dart/gui/osg/render/PointCloudShapeNode.hpp, examples/point_cloud/main.cpp
This PR enables `PointCloudShape` to specify the color and the shape type.
***
=> Add shape type and color options to PointCloudShape

CHANGELOG.md, dart/dynamics/PointCloudShape.hpp, dart/gui/osg/render/PointCloudShapeNode.cpp, examples/point_cloud/main.cpp
=> Fix handling color mode of PointCloudShape in OSG

CHANGELOG.md, python/dartpy/common/module.cpp, python/dartpy/dynamics/BodyNode.cpp, python/dartpy/dynamics/Entity.cpp, python/dartpy/dynamics/Frame.cpp, python/dartpy/dynamics/JacobianNode.cpp, python/dartpy/dynamics/MetaSkeleton.cpp, python/dartpy/dynamics/Node.cpp, python/dartpy/dynamics/ReferentialSkeleton.cpp, python/dartpy/dynamics/Skeleton.cpp, python/dartpy/dynamics/module.cpp, python/dartpy/gui/osg/Viewer.cpp, python/examples/CMakeLists.txt, python/examples/operational_space_control/CMakeLists.txt, python/examples/operational_space_control/main.py, python/tests/CMakeLists.txt, python/tests/unit/dynamics/test_body_node.py
The operational space control now can be written as easy as a few lines of Python code:
```python
class HelloWorldNode(dart.gui.osg.RealTimeWorldNode):
def __init__(self, world, kr5, target_pose = [0.3, 0.3, 0.3]):
super(HelloWorldNode, self).__init__(world)
self.kr5 = kr5
self.dofs = self.kr5.getNumDofs()
self.ee = kr5.getBodyNode('palm')
self.target_pose = target_pose
self.Kp = np.eye(3) * 50.0
self.Kd = np.eye(self.dofs) * 5.0
def customPreStep(self):
M = self.kr5.getMassMatrix()
J = self.ee.getLinearJacobian()
Jt = J.transpose();
JJt = np.matmul(J, Jt)
kI = 0.0025 * np.eye(3)
invJ = np.matmul(Jt, np.linalg.inv(JJt + kI))
dJ = self.ee.getLinearJacobianDeriv()
dJt = dJ.transpose()
dJdJt = np.matmul(dJ, dJt)
invdJ = np.matmul(dJt, np.linalg.inv(dJdJt + kI))
e = self.target_pose - …
```
=> pydart: Add JacobianNode and operational space controller example

CHANGELOG.md, dart/gui/osg/Viewer.cpp, python/dartpy/dynamics/Chain.cpp, python/dartpy/dynamics/Linkage.cpp, python/dartpy/dynamics/Skeleton.cpp, python/dartpy/simulation/World.cpp, python/examples/hello_world/main.py, python/examples/hello_world_gui/main.py, python/examples/operational_space_control/main.py, python/tests/unit/dynamics/test_meta_skeleton.py, python/tests/unit/simulation/test_world.py
API changes:
```python
import dartpy as dart
world = dart.simulation.World.create()
skel = dart.dynamics.Skeleton.create()
world.addSkeleton(skel)
chain = dart.dynamics.Chain(shoulder, elbow, dart.dynamics.Chain.IncludeUpstreamParentJointTag.IncludeUpstreamParentJoint)
world = dart.simulation.World()
skel = dart.dynamics.Skeleton()
world.addSkeleton(skel)
chain = dart.dynamics.Chain(shoulder, elbow, True)  # or chain = dart.dynamics.Chain(shoulder, elbow, includeUpstreamParentJoint=True)
```
***
=> [dartpy] Remove static create() functions in favor of custom custructors

CHANGELOG.md, dart/dynamics/Entity.hpp, dart/dynamics/Frame.cpp, dart/dynamics/Frame.hpp, dart/dynamics/SimpleFrame.hpp, python/dartpy/dynamics/Entity.cpp, python/dartpy/dynamics/Frame.cpp, python/dartpy/dynamics/ShapeFrame.cpp, python/dartpy/dynamics/SimpleFrame.cpp, python/dartpy/dynamics/module.cpp, python/dartpy/eigen_geometry_pybind.cpp, python/examples/operational_space_control/main.py, python/tests/unit/dynamics/test_simple_frame.py
=> [dartpy] Add SimpleFrame

CHANGELOG.md, dart/dynamics/FreeJoint.cpp, dart/dynamics/FreeJoint.hpp, python/dartpy/dynamics/FreeJoint.cpp, python/dartpy/dynamics/InverseKinematics.cpp, python/dartpy/dynamics/JacobianNode.cpp, python/dartpy/dynamics/Skeleton.cpp, python/dartpy/dynamics/module.cpp, python/dartpy/eigen_geometry_pybind.cpp, python/dartpy/optimizer/GradientDescentSolver.cpp, python/dartpy/optimizer/NloptSolver.cpp, python/dartpy/optimizer/Solver.cpp, python/tests/unit/dynamics/test_inverse_kinematics.py, python/tests/unit/dynamics/test_joint.py, python/tests/unit/dynamics/test_skeleton.py
=> [dartpy] Add basic inverse kinematics APIs

CHANGELOG.md, dart/dynamics/PointCloudShape.hpp, dart/gui/osg/GridVisual.cpp, dart/gui/osg/render/PointCloudShapeNode.cpp, dart/gui/osg/render/VoxelGridShapeNode.cpp, dart/gui/osg/render/VoxelGridShapeNode.hpp, examples/point_cloud/main.cpp
=> Improve voxel rendering by using multiple nodes instead of CompositeShape

CHANGELOG.md, dart/collision/ode/detail/OdeMesh.cpp
Meshes with multiple submeshes are not handled properly when using ODE as the collision detector. This is because the indices for each submesh start from 0 in Assimp, but the input to ODE requires the vertices and indices of all submeshes to be merged.
The issue can manifest itself in various ways, but the simplest example I came up with is to create a plane and a box in one mesh and have a sphere fall onto the plane.
**Before**
**After**
I have attached the mesh for reference
[plane_with_box.zip](https://github.com/dartsim/dart/files/3218953/plane_with_box.zip)
=> Fix handling of submeshes

CHANGELOG.md, python/dartpy/collision/BulletCollisionDetector.cpp, python/dartpy/collision/CollisionGroup.cpp, python/dartpy/collision/DARTCollisionDetector.cpp, python/dartpy/collision/DistanceOption.cpp, python/dartpy/collision/DistanceResult.cpp, python/dartpy/collision/OdeCollisionDetector.cpp, python/dartpy/collision/RaycastOption.cpp, python/dartpy/collision/RaycastResult.cpp, python/dartpy/collision/module.cpp, python/tests/unit/collision/test_collision.py
=> [dartpy] Add raycast option and result

CHANGELOG.md, dart/collision/RaycastResult.cpp, dart/collision/RaycastResult.hpp, unittests/comprehensive/test_Raycast.cpp
Necessary to initialize the members. Also, `RayHit.mHasHit` is removed since it's not used.
***
=> Add default constructor to RayHit

CHANGELOG.md, examples/hubo_puppet/main.cpp, python/dartpy/dynamics/Shape.cpp, python/dartpy/gui/osg/GUIEventHandler.cpp, python/dartpy/gui/osg/Viewer.cpp, python/dartpy/gui/osg/module.cpp, python/dartpy/optimizer/Function.cpp, python/examples/biped_stand/main.py
=> [dartpy] Add GUI event handler

CHANGELOG.md, dart/gui/osg/WorldNode.cpp, examples/CMakeLists.txt, examples/biped_stand/CMakeLists.txt, examples/biped_stand/README.md, examples/biped_stand/main.cpp, python/dartpy/gui/osg/ShadowTechnique.cpp, python/examples/biped_stand/main.py, python/examples/rigid_cubes/main.py
**Changes**
* Add shadow technique
* Add OSG biped example
* Reduced default shadow map resolution
***
=> dartpy: Add shadow technique

CHANGELOG.md, dart/dynamics/PointCloudShape.hpp, dart/gui/osg/ShapeFrameNode.cpp, dart/gui/osg/render/PointCloudShapeNode.cpp, dart/gui/osg/render/PointCloudShapeNode.hpp, examples/point_cloud/main.cpp
=> Adding vertex mode for point cloud shape

CHANGELOG.md, dart/gui/osg/Viewer.cpp, dart/gui/osg/Viewer.hpp
=> Fix memory leaks from dart::gui::osg::Viewer (#1331)

CHANGELOG.md, dart/collision/bullet/BulletCollisionDetector.cpp, dart/common/detail/sub_ptr.hpp, dart/common/sub_ptr.hpp, dart/dynamics/detail/BodyNodePtr.hpp, dart/dynamics/detail/GenericJointAspect.hpp, dart/dynamics/detail/PlanarJointAspect.cpp, dart/dynamics/detail/PlanarJointAspect.hpp, dart/dynamics/detail/TranslationalJoint2DAspect.cpp, dart/dynamics/detail/TranslationalJoint2DAspect.hpp, dart/utils/VskParser.cpp, examples/heightmap/main.cpp
* Fix redundant use of `std::move()` in return statement
* Obey the rule of three when the custom copy constructor is defined
***
=> Fix compilation warnings with GCC 9.1

CHANGELOG.md, dart/dynamics/PointMass.cpp, dart/dynamics/SoftBodyNode.cpp
The soft body simulation behaves unexpectedly when the simulation option is `resetCommand = false`. The root cause was that the internal forces of point masses, which are used for soft body simulation, are not reset to zero in every simulation step. In the rigid body case, this issues doesn't happen because the internal forces are set to the control command. Soft body, however, doesn't have control command API so it keeps the previous value, and this leads to the unexpected behavior.
This PR fixes the issue by always setting the internal forces of point mass to zero regardless of the `resetCommand` option.
Resolves #1370 
***
=> Reset internal force of point mass before every simulation step

CHANGELOG.md, dart/constraint/ContactConstraint.cpp, dart/constraint/ContactConstraint.hpp, dart/constraint/SoftContactConstraint.cpp, dart/constraint/SoftContactConstraint.hpp, dart/dynamics/BodyNode.cpp, dart/dynamics/BodyNode.hpp, dart/dynamics/detail/BodyNodeAspect.hpp, python/dartpy/collision/BulletCollisionDetector.cpp, python/dartpy/collision/BulletCollisionGroup.cpp, python/dartpy/collision/OdeCollisionDetector.cpp, python/dartpy/collision/OdeCollisionGroup.cpp, python/dartpy/dynamics/BodyNode.cpp, python/dartpy/optimizer/NloptSolver.cpp, tutorials/tutorial_collisions/main.cpp, tutorials/tutorial_collisions_finished/main.cpp, unittests/comprehensive/CMakeLists.txt, unittests/comprehensive/test_Friction.cpp, unittests/regression/test_Issue1184.cpp
`DynamicAspect` was introduced to allow to set different dynamics properties (including friction and restitution properties) per shape in a `BodyNode` for setting the dynamic properties of individual shapes in a `BodyNode`. However, the constraint solver still uses the dynamics properties stored in `BodyNode`.
This PR deprecates the friction and restitution property related APIs in `BodyNode` and change the constraint solver to use the dynamics properties in `DynamicAspect`.
Resolves #200.
***
=> Fix friction and restitution of individual shapes in a body

CHANGELOG.md, cmake/DARTFindDependencies.cmake
Recent the Homebrew bottles for octomap and fcl seems to work on macOS.
Resolves https://github.com/dartsim/dart/issues/1078
***
=> Enable octomap support on macOS

python/dartpy/dynamics/Joint.cpp, python/tests/unit/dynamics/test_joint.py
For now, those Isometry transformations could only be set, but not read.
1. Add wrapper to add get functionality.
2. Add python unittest to verify, that it is available and returns the same Isometry3.
[Remove this line and describe this pull request. Link to relevant GitHub issues, if any.]
***
=> Add dartpy access to getTransformFrom{Parent|Child}BodyNode()

python/dartpy/CMakeLists.txt
[They are set by `pybind11_add_module()`](https://github.com/pybind/pybind11/blob/2a5a5ec0a47c245fbf1bb1a8a90b4c3278e01693/tools/pybind11Tools.cmake#L139-L140).
***
=> Remove specifying suffix and prefix of python module

CHANGELOG.md, dart/gui/osg/render/LineSegmentShapeNode.cpp
`LineSegmentShapeNode` keeps adding new line segments instead of refreshing with new line. See the details in #1380 and [this post](https://dartsim.discourse.group/t/setting-datavariance-dynamic-causes-simulation-to-slow-and-then-stop/95).
Resolves #1380.
***
=> Fix refresh of LineSegmentShapeNode

CHANGELOG.md, dart/utils/sdf/SdfParser.cpp
=> Create dynamics aspect for collision shape in sdf parser

dart/utils/sdf/SdfParser.cpp, data/sdf/test/test_skeleton_joint.world, unittests/unit/test_SdfParser.cpp
- Parse joint friction, spring_stiffness, spring_reference
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>
Resolve #1382 
***
=> Parse sdf's joint dynamics completely

python/dartpy/dynamics/BodyNode.cpp, python/tests/unit/dynamics/test_body_node.py
- Add pybind11 wrapper for `getChildBodyNode(szd::size_t index) -> BodyNode*`
- Add pybind11 wrapper for `getChildJoint(szd::size_t index) -> Joint*`
- Add unit test, verifying that the new wrappers work
***
=> Add pybind wrappers for BodyNode's getChildBodyNode() & getChildJoint()

python/dartpy/dynamics/MetaSkeleton.cpp, python/dartpy/dynamics/Skeleton.cpp
`getGravityForces()` and `getExternalForces()` are fixed in
`dartpy.dynamics.MetaSkeleton` and `dartpy.dynamics.Skeleton`.
The wrong functions were called.
***
=> Fix typos in wrappers of dartpy Skeletons

colcon.pkg
We have been using [colcon](https://colcon.readthedocs.io/en/released/index.html) to build gazebo and ignition packages from source in a workspace, similar to using catkin-tools with a catkin workspace. A cool feature of colcon is that it can automatically identify cmake dependencies based on the cmake project name and build packages in the workspace in the correct order without creating `package.xml` files.
* https://github.com/colcon/colcon-cmake/blob/master/colcon_cmake/package_identification/cmake.py#L132-L135
If a `package.xml` file is present in a package, it will use that instead of the automatic detection, so you can build a mixed workspace of plain cmake and ROS1 or ROS2 packages.
When attempting to use colcon in a workspace with ign-physics, dartsim, bullet, and ODE, it was not …
=> Support colcon workspace with bullet and ode

python/dartpy/dynamics/ReferentialSkeleton.cpp, python/dartpy/dynamics/Skeleton.cpp, python/tests/unit/dynamics/test_skeleton.py
Before, it was only possible to access multiple `BodyNode`s by name
***
=> Add wrapper to get all `BodyNode`s from a `Skeleton`

.azure-pipelines.yml, cmake/DARTFindBullet.cmake
I see a configuration error on windows when trying to build dart with bullet3 installed from `vcpkg`:
~~~
CMake Error at cmake/DARTFindBullet.cmake:16 (set_target_properties):
Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
"optimized".  The INTERFACE_LINK_LIBRARIES property may contain
configuration-sensitive generator-expressions which may be used to specify
per-configuration rules.
~~~ 
There are multiple optimized and debug libraries interleaved in the `BULLET_LIBRARIES` parameter, so we can't use the simple approach from https://github.com/dartsim/dart/commit/73ef8c2716b37ad8a1fdd5d1468eb88841408ec2. I've used `cmake_parse_arguments` to separate the `debug` and `optimized` libraries, and I think I set up the generator expressions correctly, but I'm not sure. I've …
=> FindBullet: separate win32 optimized and debug libraries

.appveyor.yml, dart/dynamics/SharedLibraryIkFast.cpp, dart/utils/XmlHelpers.cpp, unittests/comprehensive/test_MultiObjectiveOptimization.cpp
[Build log of the warnings](https://dev.azure.com/dartsim/dart/_build/results?buildId=1587&view=logs&jobId=3bcc548c-0df3-5c60-b8ef-b9233b9b23f1&taskId=5d8baed6-9a20-5b12-6996-82143a809734&lineStart=268&lineEnd=269&colStart=1&colEnd=1)
***
=> Fix compilation warnings from VS2019

CHANGELOG.md, dart/dynamics/SharedLibraryIkFast.cpp, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/DartLoader.hpp, unittests/unit/test_DartLoader.cpp
The root joint type cannot be specified when the URDF doesn't contain "world" link. In that case, the URDF parser in DART assumes the root joint type as "free" joint, but some user could expect it to be "fixed" joint.
This PR makes that behavior configurable using flags.
***
=> Add option for parsing root joint type without world link

CHANGELOG.md, dart/utils/urdf/DartLoader.cpp, unittests/unit/test_DartLoader.cpp
=> Enable URDF parser to read visual and collision names

CHANGELOG.md, dart/common/Uri.cpp, dart/constraint/BallJointConstraint.cpp, dart/constraint/BallJointConstraint.hpp, dart/constraint/ConstraintBase.cpp, dart/constraint/ConstraintBase.hpp, dart/constraint/ContactConstraint.cpp, dart/constraint/ContactConstraint.hpp, dart/constraint/JointCoulombFrictionConstraint.cpp, dart/constraint/JointCoulombFrictionConstraint.hpp, dart/constraint/JointLimitConstraint.cpp, dart/constraint/JointLimitConstraint.hpp, dart/constraint/MimicMotorConstraint.cpp, dart/constraint/MimicMotorConstraint.hpp, dart/constraint/ServoMotorConstraint.cpp, dart/constraint/ServoMotorConstraint.hpp, dart/constraint/SoftContactConstraint.cpp, dart/constraint/SoftContactConstraint.hpp, dart/constraint/WeldJointConstraint.cpp, dart/constraint/WeldJointConstraint.hpp, examples/deprecated_examples/glut_human_joint_limits/HumanArmJointLimitConstraint.cpp, examples/deprecated_examples/glut_human_joint_limits/HumanArmJointLimitConstraint.hpp, python/dartpy/constraint/ConstraintBase.cpp, python/dartpy/constraint/ConstraintSolver.cpp, python/dartpy/constraint/JointConstraint.cpp, python/tests/unit/constraint/test_constraint.py
=> Add type property to constraint classes

CHANGELOG.md, dart/dynamics/detail/GenericJoint.hpp, unittests/comprehensive/test_Joints.cpp
This PR is a rework of #1374.
Resolves #869 
***
=> Allow to set joint rest position out of joint limits

.github/workflows/ccpp.yml, CHANGELOG.md, dart/common/SharedLibrary.cpp, dart/common/SharedLibrary.hpp, dart/common/detail/SharedLibraryManager.cpp, dart/common/detail/SharedLibraryManager.hpp
=> Remove use of boost::filesystem in public APIs

.ci/install_osx.sh
The osx CI is failing in #1424 complaining about running as root:
~~~
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
~~~
So I've removed the `sudo` calls from the install_osx script and CI is now passing.
***
=> install_osx: try removing sudo from brew commands

CHANGELOG.md, dart/constraint/ContactConstraint.cpp, dart/constraint/ContactConstraint.hpp, dart/dynamics/ShapeFrame.cpp, dart/dynamics/ShapeFrame.hpp, dart/dynamics/detail/ShapeFrameAspect.hpp, unittests/comprehensive/test_Friction.cpp
Currently the ContactConstraint uses a friction pyramid with 2 directions, and it uses the same friction coefficient in each direction. We have found it useful in gazebo to be able to specify different values in each direction (anisotropic wheel friction for example). As such, I've added `mSecondaryFrictionCoeff` to the ShapeNode DynamicsAspect and updated the ContactConstraint to use this secondary coefficient. @azeey and I have additional code in his fork that adds parameters for specifying the friction directions and slip parameters, which will be addressed in subsequent pull requests.
[edited] To avoid a behavior change, the `mFrictionCoeff` member variable in the ShapeFrame DynamicsAspect is renamed to `mPrimaryFrictionCoeff` along with its auto-generated get/set functions. The …
=> Add secondary friction coefficient parameter

CHANGELOG.md, dart/constraint/ContactConstraint.cpp, dart/constraint/ContactConstraint.hpp, dart/dynamics/ShapeFrame.cpp, dart/dynamics/ShapeFrame.hpp, dart/dynamics/detail/ShapeFrameAspect.hpp, unittests/comprehensive/test_Friction.cpp
Currently the ContactConstraint uses a friction pyramid with 2 directions. In #1424, we added an additional parameter to allow the friction coefficient to be specified separately in each direction. This pull request allows the friction direction to be specified with a unit vector `FirstFrictionDirection` and pointer to a frame `FirstFrictionDirectionFrame` in which the unit vector is expressed. If `FirstFrictionDirection` is a vector of zeros (which is its default value), it is ignored and the default friction directions are used. If the frame pointer is `nullptr` (which is its default value), the body-fixed frame of that ShapeNode is used.
I've added two bodies to `test_Friction` with friction direction set using the default body-fixed frame and also using the world frame. In these …
=> Add friction direction unit vector and frame parameters

CHANGELOG.md, python/dartpy/gui/osg/InteractiveFrame.cpp, python/dartpy/gui/osg/Viewer.cpp, python/examples/drag_and_drop/main.py
Enabling drag and drop for InteractiveFrame currently doesn't work as expected because of the order of Python bindings for `dart::gui::osg::Viewer::enableDragAndDrop(...)`. [pybind11 calls earlier-defined overloads](https://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order). For `InteractiveFrame` case, `enableDragAndDrop(Entity*)` is called instead of `enableDragAndDrop(InteractiveFrame*)` because `enableDragAndDrop(Entity*)` is defined in prior to the other (and it's compatible since `Entity` is a base of `InteractiveFrame`). To prevent this, this PR defines `enableDragAndDrop(InteractiveFrame*)` (and other functions overloaded for derived classes of `Entity`) before `enableDragAndDrop(Entity*)`.
***
**Before merging a …
=> [dartpy] Fix enabling drag and drop of InteractiveFrame

CHANGELOG.md, CMakeLists.txt, cmake/DARTConfig.cmake.in
Fixes #1429 
***
- [N/A] Document new methods and classes
- [N/A] Add unit test(s) for this change
=> Add support new if() IN_LIST operator in DARTConfig.cmake

CHANGELOG.md, dart/gui/osg/ImGuiHandler.cpp
This PR fixes that modifier keys were not correctly hooked for ImGuiHandler.
***
- [N/A] Add unit test(s) for this change
=> Add modifier key support to ImGuiHandler

CHANGELOG.md
=> Update changelog for DART 6.9: switched to C++14

CHANGELOG.md, dart/dynamics/Skeleton.cpp, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue1445.cpp
An issue with auto-updating collisions was found in [ign-physics](https://github.com/ignitionrobotics/ign-physics/pull/31). This PR ports the fix into DART itself.
I will be pushing a regression test for this issue shortly.
***
=> Increment body node version after it has been moved to a new skeleton

.ci/install_osx.sh, Brewfile
This should fix the CI error on macOS.
=> Install numpy using pip3 instead of Homebrew

CHANGELOG.md, dart/collision/fcl/BackwardCompatibility.hpp, dart/collision/fcl/FCLCollisionDetector.cpp, data/skel/shapes.skel, unittests/comprehensive/test_Collision.cpp
The sphere was used for ConeShape when FCLCollisionDetector is used. This PR changed to use mesh for ConeShape as other shapes in FCLCollisionDetector.
***
=> Add ConeShape support for FCLCollisionDetector

CHANGELOG.md, dart/dynamics/Skeleton.hpp, dart/dynamics/detail/GenericJoint.hpp, doxygen/Doxyfile.in, unittests/comprehensive/test_Dynamics.cpp
This PR fixes incorrect implicit joint damping/spring forces in inverse dynamics computation.
Fixes #1450 
***
=> Fix inverse dynamics with damping and stiffness

CHANGELOG.md, dart/dynamics/IkFast.cpp, dart/dynamics/IkFast.hpp, unittests/unit/test_IkFast.cpp
IKFast sometimes returns solutions that are not wrapped within the range of the joint limits, which is regarded as an invalid solution in DART.
This PR fixes the issue by adding logic that tries to wrap IKFast solutions for rotational joints. The idea is to wrap the solution within joint limits. If there is more than one solution (when the joint limit range is wider than 2pi), it returns the closest solution to the current joint position to minimize joint motion.
The logic should be applied to any DegreeOfFreedom whose configuration space is SO(2), but this PR only applies it to RevoluteJoint. This is because the current API doesn't provide for it. `DegreeOfFreedom::isCyclic()` is the closest function to what we want, but it only returns true when the rotational joint has no limits.
This …
=> Wrap IKFast solutions for cyclic joint positions

.github/workflows/ccpp.yml
To suppress build error: https://github.com/dartsim/dart/runs/621262581?check_suite_focus=true#step:3:1096
=> Build without ODE on Windows CI builds

CHANGELOG.md, python/dartpy/collision/CollisionResult.cpp, python/dartpy/dynamics/Shape.cpp, python/examples/contacts_pointcloud/main.py
1. Adds Python bindings for the following:
- Extracting contacts from `CollisionResult` object (Methods `getContact` and `getContacts`)
- `PointCloudShape`, so it is now possible to draw pointclouds in dartpy as well
2. Adds an example `python/examples/contacts_pointcloud/main.py`, which is basically the `hello_world_gui` example (robot and ground are set transparent) with detection of  contacts and visualization as a pointcloud before each GUI refresh.
***
=> Add python bindings for pointcloud and contact retrieval

.azure-pipelines.yml, cmake/DARTFindurdfdom.cmake, cmake/FindTinyXML.cmake
=> Add workaround for invalid path in finding urdfdom on Windows

CHANGELOG.md, dart/constraint/BoxedLcpConstraintSolver.cpp
This PR fixes a small allocation bug in BoxedLcpConstraintSolver. This was bothering me for several months. I managed to pin-point it. This is very apparent if one uses many mimic joints (and thus creates many constraints).
=> Fix small bug in BoxedLcpConstraintSolver

CHANGELOG.md, python/dartpy/dynamics/BodyNode.cpp, python/dartpy/dynamics/Node.cpp, python/dartpy/dynamics/pointers.hpp, python/tests/unit/dynamics/test_body_node.py
`dartpy.dynamics.Node.getBodyNodePtr()` causes TypeError as
```python
>>> b.getBodyNodePtr()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
(self: dartpy.dynamics.Node) -> dart::dynamics::TemplateBodyNodePtr<dart::dynamics::BodyNode>
```
This was because `dart::dynamics::TemplateBodyNodePtr<dart::dynamics::BodyNode>` is declared after the `Node` binding. This PR fixes it by declaring the holder type at the top of dynamics submodule.
This PR needs to be merged before #1457.
***
=> Fix TypeError from dartpy.dynamics.Node.getBodyNodePtr()

CMakeLists.txt
Fixes #1477.
Without this change, it ignores `CMAKE_INSTALL_PREFIX` values specified by the user and always installs to `C:/Golems`.
=> Don't force CMAKE_INSTALL_PREFIX on windows

.ci/install_osx.sh, Brewfile, CHANGELOG.md, dart/gui/osg/CMakeLists.txt, examples/speed_test/main.cpp
OpenSceneGraph 3.6.5 or less are not compatible with macOS 10.15 (Catalina) or greater (https://github.com/openscenegraph/OpenSceneGraph/issues/926, https://github.com/dartsim/dart/issues/1439). This PR increases the required minimum OSG version for macOS Catalina to 3.7.0 that includes the [fix](https://github.com/openscenegraph/OpenSceneGraph/pull/944).
Resolves #1439
***
=> Enforce to use OSG 3.7.0 or greater on macOS Catalina

.azure-pipelines.yml, .ci/docker/Dockerfile.ubuntu-eoan, .ci/install_linux.sh, .github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/ccpp.yml, CHANGELOG.md, dart/collision/fcl/BackwardCompatibility.hpp, dart/collision/fcl/FCLCollisionDetector.cpp, dart/constraint/BoxedLcpConstraintSolver.cpp, dart/dynamics/PyramidShape.cpp, dart/dynamics/PyramidShape.hpp, dart/dynamics/Shape.hpp, dart/gui/OpenGLRenderInterface.cpp, dart/gui/OpenGLRenderInterface.hpp, dart/gui/RenderInterface.cpp, dart/gui/RenderInterface.hpp, dart/gui/glut/SimWindow.cpp, dart/gui/osg/ShapeFrameNode.cpp, dart/gui/osg/render/PyramidShapeNode.cpp, dart/gui/osg/render/PyramidShapeNode.hpp, dart/utils/SkelParser.cpp, data/skel/shapes.skel
This PR adds the pyramid shape that has a square base. Currently, only FCL supports the shape for collision detection. Like other primitive shapes, the pyramid shape is converted to equivalent mesh with minimal numbers of vertices and faces. Both GLUT and OSG renderer can render the pyramid shape.
The moments of inertia for the pyramid shape is not implemented in this PR.
***
=> Add pyramid shape support

CHANGELOG.md, python/dartpy/collision/DistanceResult.cpp
Adding pybind/eigen.h to allow read/write of eigen types in DistanceResult
=> Added pybind eigen header to dartpy DistanceResult

docs/readthedocs/tutorials/biped.md, docs/readthedocs/tutorials/collisions.md, docs/readthedocs/tutorials/multi-pendulum.md
Update tutorial text to use current API for visualization aspects on shape nodes
***
=> Fix: update tutorial doc to reflect new APIs

CHANGELOG.md, dart/gui/glut/MotionBlurSimWindow.cpp, dart/gui/glut/Win3D.cpp
This PR fixes the incorrect projection matrix computation in OpenGL due to the misplaced `gluLookAt()` calls.
Fixes #1484.
***
=> Fix mixed intrinsic and extrinsic camera parameters in OpenGL projection matrix

CHANGELOG.md, python/dartpy/collision/CollisionGroup.cpp, python/dartpy/dynamics/InverseKinematics.cpp, python/dartpy/gui/osg/Viewer.cpp, python/tests/unit/collision/test_collision.py
This PR adds the following Python bindings for
- `dart::collision::CollisionGroup::addShapeFramesOf(...)`
- `dart::collision::ShapeFrame::removeShapeFramesOf(...)`
- group-group collision checking
- `dart::gui::osg::Viewer::frame()`
***
=> Add python bindings for adding ShapeFrames to CollisionGroup

cmake/DARTConfig.cmake.in, cmake/DARTFindBullet.cmake
In DART 6.9.3, the `IN_LIST` keyword in DARTFindBullet caused a configuration error in gazebo10 (see https://github.com/osrf/gazebo/pull/2835). Setting `CMP0057` to new should prevent similar problems in downstream packages.
***
=> Support IN_LIST operator in DARTConfig.cmake (6.9 backport)

CHANGELOG.md, dart/gui/osg/ImGuiHandler.cpp
=> Enable mouse middle and right buttons for ImGui

.github/workflows/ccpp.yml, CMakeLists.txt, dart/CMakeLists.txt
clang-cl is the Visual Studio-compatible version of clang (https://clang.llvm.org/docs/MSVCCompatibility.html).
This PR: 
* Enables compilation of DART even for VS < 2019 if Clang is used (as clang-cl can be perfectly C++14 compatible even if the used MSVC version is not)
* Avoid to pass the /MP option to clang-cl that does not support it
* Adds a GitHub Actions job to compile DART with clang-cl (using in particular the ClangCl toolset shipped with MSVC)
=> Fix compatibility with clang-cl

.github/workflows/ccpp.yml, cmake/Findassimp.cmake, cmake/Findfcl.cmake
This PR fixes the linking of tests that use fcl and assimp on MSVC, hopefully fixing the problems reported in https://github.com/ignitionrobotics/ign-physics/issues/87#issuecomment-705155086 .
As the existing code is working well in CI for non-MSVC platforms, and as support for CMake imported targets can vary depending on the platform (for example, `assimp::assimp` is basically broken in Ubuntu 20.04 apt packages: https://bugs.launchpad.net/ubuntu/+source/assimp/+bug/1882427 and https://github.com/robotology/idyntree/issues/693), to minimize the possible regressions I just used the imported targets for fcl and assimp when using MSVC.
=> Fix MSVC linking for assimp and fcl

.azure-pipelines.yml, .ci/azure-pipelines/docker.yml, .ci/docker/Dockerfile.ubuntu-bionic, .ci/docker/Dockerfile.ubuntu-focal, .ci/docker/Dockerfile.ubuntu-groovy, .ci/docker/Dockerfile.ubuntu-trusty, .ci/docker/Dockerfile.ubuntu-xenial, .ci/docker/Dockerfile.ubuntu-xenial-32bit, .ci/install_linux.sh, .github/workflows/ccpp.yml, .travis.yml
The Docker images are hosted on https://hub.docker.com/repository/docker/dartsim/dart-dev, and the source code repo is https://github.com/dartsim/dart-ci-docker-containers
=> Use prebuilt Ubuntu Docker images for CIs

dart/common/AspectWithVersion.hpp
*Note: There are other errors that still need to be resolved before* `/permissive-` *is no longer needed on Windows*.
Using DART (master) in a project on Windows yields the following compile error:
```
2>C:\...\include\dart/common/AspectWithVersion.hpp(94): error C2974: 'dart::common::detail::AspectWithState': invalid template argument for 'CompositeT', type expected
2>  C:\...\include\dart/common/detail/AspectWithVersion.hpp(53): note: see declaration of 'dart::common::detail::AspectWithState'
2>  C:\...\include\dart/dynamics/EndEffector.hpp(57): note: see reference to class template instantiation 'dart::common::AspectWithStateAndVersionedProperties<dart::dynamics::Support,dart::dynamics::detail::SupportStateData,dart::dynamics::detail::SupportPropertiesData,dart::dynamics::EndEffector,da …
```
=> Windows compile fix: Be more specific about which AspectWithState to use

dart/common/RequiresAspect.hpp
Leftover from https://github.com/dartsim/dart/pull/1541 .
=> Add missing virtual base class dectoration for RequiresAspect

dart/collision/bullet/BulletCollisionDetector.cpp
=> Print warning once from BulletCollisionDetector::collide/distance

.github/workflows/ccpp.yml, dart/dynamics/InverseKinematics.cpp, dart/dynamics/InverseKinematics.hpp, python/dartpy/dynamics/InverseKinematics.cpp
This PR is to allow `TaskSpaceRegion` to specify the reference frame for computing errors in the task space. This PR replaces #1430 based on the discussion in the PR.
***
=> Allow specifying reference frame for TaskSpaceRegion

cmake/DARTMacros.cmake
Add DART_SKIP_<dep> option to permit to specify that a dependency should not used even if it is found in the system.
This is useful in package managers such as vcpkg to ensure that, for a given set of enabled features, the same version of the library is build, independently from which dependency are actually installed in the system. A mpre extended rationale is provided in https://github.com/ignitionrobotics/ign-cmake/issues/63 .
=> CMake: Add DART_SKIP_<dep> advanced options

CHANGELOG.md, dart/collision/bullet/BulletCollisionDetector.cpp, dart/collision/bullet/detail/BulletOverlapFilterCallback.cpp, dart/collision/bullet/detail/BulletOverlapFilterCallback.hpp, unittests/comprehensive/test_Collision.cpp
=> Fix incorrect group-group collision checking for BulletCollisionDetector

CHANGELOG.md, dart/constraint/JointConstraint.cpp, dart/utils/sdf/SdfParser.cpp, data/sdf/test/test_issue1596.model, package.xml, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue1596.cpp, unittests/unit/test_Signal.cpp
* Fix incorrect LCP construction in `JointConstraint` for multi-DOFs joints (fixes #1596)
* Add `universal` joint type in `SDFParser`
* Encode visual/collision name attribute of SDF in ShapeNode name
* Bump version to 6.11.1
***
=> Fix incorrect LCP construction in JointConstraint for multi-DOFs joints (#1596)

CHANGELOG.md, dart/utils/urdf/DartLoader.cpp, dart/utils/urdf/DartLoader.hpp, python/dartpy/utils/DartLoader.cpp, unittests/unit/test_DartLoader.cpp
Enable to pass parsing options to `DartLoader`. Currently the options are default resource retriever, default root joint type, and default inertia of link. The default inertia options is to resolve #1604.
***
=> Add default options to DartLoader for missing properties in URDF files

dart/constraint/JointLimitConstraint.cpp, dart/utils/XmlHelpers.cpp, dart/utils/mjcf/MjcfParser.cpp, dart/utils/mjcf/detail/Body.cpp, dart/utils/mjcf/detail/BodyAttributes.cpp, dart/utils/mjcf/detail/Default.cpp, dart/utils/mjcf/detail/Geom.cpp, dart/utils/mjcf/detail/Inertial.cpp, dart/utils/mjcf/detail/Mesh.cpp, dart/utils/mjcf/detail/MujocoModel.cpp, dart/utils/mjcf/detail/Site.cpp, dart/utils/mjcf/detail/Utils.cpp, dart/utils/mjcf/detail/Weld.cpp, dart/utils/urdf/DartLoader.cpp, tools/cpplint.py
`not` operator isn't compatible in some build environments. No reason to use the _alternative_ operators.
***
=> Replace not operator with !

CHANGELOG.md, dart/dynamics/Joint.cpp, dart/dynamics/Joint.hpp, data/sdf/test/force_torque_test.world, unittests/comprehensive/CMakeLists.txt, unittests/comprehensive/test_JointForceTorque.cpp
[Remove this line and describe this pull request. Link to relevant GitHub issues, if any.]
***
=> Add joint force/torque getter

CHANGELOG.md, dart/utils/sdf/SdfParser.cpp, dart/utils/sdf/SdfParser.hpp, data/sdf/test/force_torque_test2.world, python/dartpy/utils/SdfParser.cpp, unittests/comprehensive/test_JointForceTorque.cpp
=>  Allow SdfParser to set default root joint type

dart/constraint/ContactConstraint.cpp, data/sdf/test/issue1624_cubes.sdf, unittests/regression/CMakeLists.txt, unittests/regression/test_Issue1624.cpp
DART crashes when simulating a modest number of objects that come into contact with each other. 
To test, run the following file in ign-gazebo (`ign gazebo -v 4 cube5.sdf.txt`)
[cube5.sdf.txt](https://github.com/azeey/dart/files/4755483/cube5.sdf.txt) (courtesy of @mjcarroll)
Before the PR, ign-gazebo crashes with
```
ODE INTERNAL ERROR 1: assertion "bNormalizationResult" failed in _dNormalize4() [odemath.h:42]
```
With the PR:
For a given set of contact constraints, the constraint solver first creates a grouping of related constraints, and then solves each group independently. There seems to be a problem with this grouping and some constraints end up being in two groups. 
The `ContactConstraint::uniteSkeleton` function unites two skeletons associated with a given contact constraint. It …
=> Fix grouping of contact constraints

dart/constraint/BallJointConstraint.cpp, dart/constraint/JointConstraint.cpp, dart/constraint/JointCoulombFrictionConstraint.cpp, dart/constraint/JointLimitConstraint.cpp, dart/constraint/MimicMotorConstraint.cpp, dart/constraint/ServoMotorConstraint.cpp, dart/constraint/SoftContactConstraint.cpp, dart/constraint/WeldJointConstraint.cpp, dart/dynamics/detail/DegreeOfFreedomPtr.hpp, unittests/regression/test_Issue1231.cpp
- Apply #1624 for other constraints
- Fix compile warnings with GCC 11.2
***
=> Fix grouping of skeletons by constraints

dart/collision/CollisionGroup.cpp, dart/collision/CollisionGroup.hpp, dart/collision/detail/CollisionGroup.hpp, dart/constraint/ConstraintSolver.cpp, unittests/unit/test_CollisionGroups.cpp
When `subscribeTo` is called with a skeleton in `addSkeleton`, the skeleton is added to `mSkeletonSources`. However, inside `removeSkeleton`, `unsubscribeFrom` is not called. Instead, `removeShapeFrameOf` is called. This is fine for most cases, but it fails to remove the skeleton from `mSkeletonSources` if the skeleton does not have any shapes within it. This causes `mSkeletonSources` to grow indefinitely. A hazardous side effect of this is that when an attempt is made to add a new skeleton via `subscribeTo`, the address of the skeleton might be the same as one of the stale entries in `mSkeletonSources`. Consequently, the new skeleton's shapes don't get added to the collision detection engine and very surprising results follow.
Here's a print out of `mSkeletonSources` after running …
=> Fix issue with removing skeletons without shapes

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, dart/collision/bullet/BulletCollisionDetector.cpp, dart/collision/ode/OdeCollisionObject.cpp, dart/common/Castable.hpp, dart/common/Metaprogramming.hpp, dart/common/detail/Castable-impl.hpp, dart/common/detail/Metaprogramming-impl.hpp, dart/constraint/BoxedLcpSolver.hpp, dart/dynamics/Shape.hpp, dart/gui/glut/SimWindow.cpp
Add `Castable` class, a CRTP base class that provides an interface for easily casting to the derived types
***
=> Add Castable class

CHANGELOG.md, CMakeLists.txt, dart/common/CAllocator.cpp, dart/common/CAllocator.hpp, dart/common/Castable.hpp, dart/common/MemoryAllocator.cpp, dart/common/MemoryAllocator.hpp, dart/common/detail/MemoryAllocator-impl.hpp, unittests/unit/CMakeLists.txt, unittests/unit/test_CAllocator.cpp
Initial work for adding custom memory allocator:
- Add `MemoryAllocator` that is a base class for custom memory allocators
- Add `CAllocator` that is a simple wrapper of std::malloc and std::free
***
=> Add MemoryAllocator and CAllocator

CHANGELOG.md, dart/common/Stopwatch.cpp, dart/common/Stopwatch.hpp, dart/common/Timer.hpp, dart/common/detail/Stopwatch-impl.hpp, dart/simulation/World.hpp, python/dartpy/common/Stopwatch.cpp, python/dartpy/common/module.cpp, python/tests/unit/common/test_stopwatch.py, unittests/unit/common/test_Stopwatch.cpp, unittests/unit/math/test_Math.cpp
=> Add Stopwatch class to replace Timer

.github/workflows/ci_ubuntu.yml, CHANGELOG.md, dart/common/CAllocator.cpp, dart/common/CAllocator.hpp, dart/common/Castable.hpp, dart/common/FreeListAllocator.cpp, dart/common/FreeListAllocator.hpp, dart/common/Macros.hpp, dart/common/StlAllocator.hpp, dart/common/detail/Aspect.hpp, dart/common/detail/Castable-impl.hpp, dart/common/detail/StlAllocator-impl.hpp, dart/lcpsolver/ODELCPSolver.cpp, dart/optimizer/ipopt/IpoptSolver.cpp, tools/run, unittests/unit/common/test_FreeListAllocator.cpp
=> Add FreeListAllocator class

cmake/DARTFindfcl.cmake
=> Use fclConfig.cmake

examples/biped_stand/main.cpp
Quick solution to fix segfault from `biped_stand` example. `osg::ref_ptr` should be used to create `WorldNode` and to pass it to `Viewer::addWorldNode()`.
Additionally enabled 1~4 key for perturbing the robot.
***
=> Fix biped_stand example

CHANGELOG.md, dart/gui/osg/GridVisual.cpp, dart/gui/osg/Utils.hpp, dart/gui/osg/render/BoxShapeNode.cpp, dart/gui/osg/render/CapsuleShapeNode.cpp, dart/gui/osg/render/ConeShapeNode.cpp, dart/gui/osg/render/CylinderShapeNode.cpp, dart/gui/osg/render/EllipsoidShapeNode.cpp, dart/gui/osg/render/LineSegmentShapeNode.cpp, dart/gui/osg/render/MeshShapeNode.cpp, dart/gui/osg/render/MultiSphereShapeNode.cpp, dart/gui/osg/render/PlaneShapeNode.cpp, dart/gui/osg/render/PointCloudShapeNode.cpp, dart/gui/osg/render/PyramidShapeNode.cpp, dart/gui/osg/render/SoftMeshShapeNode.cpp, dart/gui/osg/render/SphereShapeNode.cpp, dart/gui/osg/render/VoxelGridShapeNode.cpp
**Summary:**
This PR fixes the issue that a transparent object is sometimes not displayed when it's behind another transparent object, which is not captured by https://github.com/dartsim/dart/pull/1414. It's fixed by two changes. Firstly, set OSG to render transparent objects after opaque objects using `setRenderingHint()` (see: [this post](https://stackoverflow.com/a/26864994/3122234)). Secondly, disable z-buffer writing while enabling z-buffer testing during drawing transparent objects so transparent objects don't get rendered when they're behind opaque object but always rendered (with blending) even when they're overlapped with other transparent objects regardless of their z-depths. See [this post](https://stackoverflow.com/a/52870474/3122234).
**Not fixed by this PR:**
Fixing for …
=> Fix depth testing for transparent objects

CHANGELOG.md, dart/common/CAllocator.cpp, dart/common/CAllocator.hpp, dart/common/FreeListAllocator.cpp, dart/common/MemoryAllocator.hpp, dart/common/PoolAllocator.cpp, dart/common/PoolAllocator.hpp, unittests/unit/common/test_PoolAllocator.cpp
=> Add PoolAllocator class

CHANGELOG.md, dart/common/CAllocator.cpp, dart/common/FreeListAllocator.cpp, dart/common/FreeListAllocator.hpp, dart/common/Macros.hpp, dart/common/MemoryAllocator.hpp, dart/common/MemoryAllocatorDebugger.hpp, dart/common/MemoryManager.cpp, dart/common/MemoryManager.hpp, dart/common/PoolAllocator.cpp, dart/common/PoolAllocator.hpp, dart/common/StlAllocator.hpp, dart/common/detail/MemoryAllocatorDebugger-impl.hpp, dart/common/detail/MemoryManager-impl.hpp, dart/constraint/ConstraintSolver.cpp, dart/constraint/ConstraintSolver.hpp, dart/constraint/detail/ConstraintSolver-impl.hpp, dart/dynamics/BodyNode.hpp, unittests/integration/test_World.cpp, unittests/unit/common/test_FreeListAllocator.cpp, unittests/unit/common/test_MemoryManager.cpp, unittests/unit/common/test_PoolAllocator.cpp, unittests/unit/common/test_StlAllocator.cpp
=> Add MemoryManager and MemoryAllocatorDebugger

CHANGELOG.md, dart/CMakeLists.txt, dart/common/Filesystem.hpp, dart/common/Optional.hpp, dart/common/SharedLibrary.cpp, dart/common/SharedLibrary.hpp, dart/common/detail/SharedLibraryManager.cpp, dart/common/detail/SharedLibraryManager.hpp, dart/gui/osg/render/MeshShapeNode.cpp, dart/utils/mjcf/detail/Body.cpp, dart/utils/mjcf/detail/Body.hpp, dart/utils/mjcf/detail/BodyAttributes.cpp, dart/utils/mjcf/detail/BodyAttributes.hpp, dart/utils/mjcf/detail/Compiler.cpp, dart/utils/mjcf/detail/Geom.cpp, dart/utils/mjcf/detail/GeomAttributes.hpp, dart/utils/mjcf/detail/Inertial.hpp, dart/utils/mjcf/detail/JointAttributes.hpp, dart/utils/mjcf/detail/MeshAttributes.hpp, dart/utils/mjcf/detail/Site.cpp, dart/utils/mjcf/detail/Site.hpp, dart/utils/mjcf/detail/Utils.cpp, dart/utils/mjcf/detail/Utils.hpp, dart/utils/mjcf/detail/Weld.cpp, dart/utils/mjcf/detail/Weld.hpp, dart/utils/mjcf/detail/WeldAttributes.hpp, dart/utils/mjcf/detail/Worldbody.cpp, dart/utils/mjcf/detail/Worldbody.hpp
=> Remove use of boost::filesystem and boost::optional

CHANGELOG.md, dart/gui/osg/CMakeLists.txt, dart/gui/osg/Utils.cpp, dart/gui/osg/Utils.hpp, dart/gui/osg/Viewer.cpp, dart/gui/osg/Viewer.hpp, dart/gui/osg/detail/CameraModeCallback.cpp, dart/gui/osg/detail/CameraModeCallback.hpp, dart/gui/osg/detail/Utils-impl.hpp, examples/atlas_simbicon/AtlasSimbiconWidget.cpp, examples/atlas_simbicon/AtlasSimbiconWidget.hpp, python/dartpy/gui/osg/Viewer.cpp
**Usage**:
```cpp
auto viewer = dart::gui::osg::Viewer();
viewer.setCameraMode(dart::gui::osg::CameraMode::DEPTH);  // or dart::gui::osg::CameraMode::RGBA (default)
```
**RGBA mode**:
**Depth mode**
***
=> Add depth rendering mode

cmake/DARTFindDependencies.cmake
Octomap support was disabled due to https://github.com/OctoMap/octomap/pull/213, but that fix has been released a long time ago and all the octomap versions available in package managers used on Windows (vcplconda-forge, conan) include it.
***
=> Use octomap also on Windows

dart/collision/bullet/BulletCollisionDetector.cpp
Create bullet convex mesh collision shape when input mesh is convex. Convex mesh colliders work much faster, also Bullet do not support concave mesh vs concave mesh collisions
=> create convex mesh when possible

CMakeLists.txt, python/CMakeLists.txt
so that building dartpy can be programmatically disabled if needed even when the deps are detected
***
=> Add DART_BUILD_DARTPY option

CMakeLists.txt, cmake/DARTFindBullet.cmake, cmake/DARTFindOpenSceneGraph.cmake, dart/common/IncludeWindows.hpp, dart/common/SharedLibrary.hpp, dart/common/Timer.hpp, dart/common/detail/SharedLibraryManager.hpp, dart/constraint/ConstraintSolver.cpp, dart/gui/osg/DefaultEventHandler.cpp, dart/gui/osg/TrackballManipulator.hpp, dart/gui/osg/render/MeshShapeNode.cpp, python/dartpy/CMakeLists.txt, python/dartpy/gui/osg/GUIEventHandler.cpp
- Use `target_link_libraries()` instead of `set_target_properties()` to handle the link-type keywords in `*_LIBRARIES` (inspired by https://github.com/PointCloudLibrary/pcl/pull/3341)
- Fix build errors on Windows + VS2022
***
=> Fix finding OSG on Windows

CMakeLists.txt, examples/atlas_simbicon/TerminalCondition.cpp, examples/deprecated_examples/glut_atlas_simbicon/TerminalCondition.cpp
=> Enable building examples and tutorials on Windows

dart/dynamics/Inertia.cpp, dart/dynamics/Inertia.hpp
* Part of https://github.com/gazebosim/gz-sim/issues/1462
* Used by https://github.com/gazebosim/gz-physics/pull/384
***
We're adding support for fluid added mass to Gazebo, see the [Fluid Added Mass Proposal](http://sdformat.org/tutorials?tut=added_mass_proposal&branch=chapulina/added_mass). This feature makes use of values in a body's spatial tensor which break the current assumptions in the inertia class. Since this is a valid use case for us, we'd like to suppress those warnings.
So far I haven't noticed any other places where DART misbehaves when passing those values to the spatial tensor. As an example, without this PR I see warnings like this:
```
Warning [Inertia.cpp:287] [Inertia::verifySpatialTensor] Invalid entry for (3,3): 0.261666. Value should be exactly zero.
Warning …
```
=> Make inertial warnings optional when setting tensor

dart/utils/mjcf/MjcfParser.cpp
- Addresses Issue #1673
- Switches to logical and rather than bitwise
***
=> Silence Clang-14 bitwise instead of logical

dart/common/IncludeWindows.hpp, dart/common/SharedLibrary.hpp, dart/common/Timer.hpp, dart/gui/LoadOpengl.hpp
=> Fix windows near far

dart/math/CMakeLists.txt, dart/math/Geometry.hpp, dart/math/Random.hpp, dart/math/TriMesh.hpp
**Change of `libdart7-math` in `Release` mode on Ubuntu**:
- Number of symbols: 1,166 -> 314
- Size of binary: 745K -> 640K
> Disclaimer: Some APIs could be hidden when they are supposed to be exported but just not caught by the CI. They will be exported eventually as discovered...
***
=> Add symbol control to dart::math

dart/CMakeLists.txt, dart/optimization/CMakeLists.txt, dart/optimization/Function.hpp, dart/optimization/GradientDescentSolver.hpp, dart/optimization/Problem.hpp, dart/optimization/Solver.hpp, dart/optimization/ipopt/IpoptSolver.hpp, dart/optimization/nlopt/NloptSolver.hpp, dart/optimization/pagmo/PagmoMultiObjectiveSolver.hpp
**Change of `libdart7-math` in `Release` mode on Ubuntu**:
- Number of symbols: 1,496 -> 561
- Size of binary: 701K -> 582K
> Disclaimer: Some APIs could be hidden when they are supposed to be exported but just not caught by the CI. They will be exported eventually as discovered...
***
=> Add symbol control to dart::optimization

dart/gui/CMakeLists.txt, dart/gui/GLFuncs.hpp, dart/gui/glut/SimWindow.hpp, dart/gui/glut/SoftSimWindow.hpp, dart/gui/glut/Win3D.hpp, dart/gui/glut/Window.hpp, dart/gui/osg/DefaultEventHandler.hpp, dart/gui/osg/DragAndDrop.hpp, dart/gui/osg/GridVisual.hpp, dart/gui/osg/ImGuiHandler.hpp, dart/gui/osg/ImGuiViewer.hpp, dart/gui/osg/ImGuiWidget.hpp, dart/gui/osg/InteractiveFrame.hpp, dart/gui/osg/RealTimeWorldNode.hpp, dart/gui/osg/SupportPolygonVisual.hpp, dart/gui/osg/Viewer.hpp, dart/gui/osg/WorldNode.hpp
**Change of `libdart7-gui` in `Release` mode on Ubuntu**:
- Number of symbols: 4,024 -> 1,665
- Size of binary: 2.6M -> 2.3M
> Disclaimer: Some APIs could be hidden when they are supposed to be exported but just not caught by the CI. They will be exported eventually as discovered...
***
=> Add symbol control to dart::gui

python/dartpy/dynamics/Skeleton.cpp, python/dartpy/dynamics/WholeBodyIK.cpp, python/dartpy/dynamics/dartpy_dynamics.cpp
Hi, I noted an error when trying to use get the InverseKinematics of a skeletion from python. 
The dart.dynamics.skel.getIK() method resulted in an error: could not be converted into a python type. 
So I added a binding for the WholeBodyIK class. This seems to fix it.
Unfortunately, I do not have the time to bind the whole class atm, so I only bound the solveAnApply method, which allows most basic usage.
Let me know if this needs some futher work before merging.
Cheers
=> Added python binding for WholeBodyIK

dart/constraint/JointConstraint.cpp
Fixes https://github.com/dartsim/dart/issues/1683
***
- ~[ ] Document new methods and classes~
=> Allow joint to recover after reaching position limits in servo mode

dart/dynamics/BodyNode.cpp, dart/dynamics/Skeleton.cpp, dart/gui/osg/Viewer.cpp, dart/gui/osg/Viewer.hpp, dart/gui/osg/detail/CameraModeCallback.cpp
Tested on 7.0 (main) with `-D_GLIBCXX_ASSERTIONS`: https://github.com/dartsim/dart/actions/runs/7258388815/job/19773633871
Resolve #1769 
***
=> Attempt to fix #1769

dart/utils/urdf/urdf_world_parser.cpp
There is a parsePose method in urdfdom 4.0.0 with the same signature as the function defined locally in urdf_world_parser, which causes build errors due to an ambiguous call. This adds `urdf_parsing::` to the reference to `parsePose` to eliminate the ambiguity. Needed for https://github.com/Homebrew/homebrew-core/pull/158963.
I was confused about why this error occurs since I don't see `using namespace urdf;` anywhere, but I believe it's due to [argument-dependent lookup](https://en.cppreference.com/w/cpp/language/adl) (thanks @azeey for the pointer).
=> Fix build with urdfdom 4.0.0

CMakeLists.txt
https://github.com/gazebosim/gz-physics/issues/662
***
=> Set DART_ENABLE_SIMD=OFF by default

.github/workflows/ci_macos.yml, .github/workflows/ci_ubuntu.yml, .github/workflows/ci_windows.yml, CHANGELOG.md, dart/gui/CMakeLists.txt, pixi.toml
The detection of GLUT is already handled by `dart_check_optional_package()` (will skip building the `osg` component), so there is no need to check it again. Additionally, the logic `if(NOT WIN32 OR CYGWIN)` is inconsistent.
As a result, `FindDARTGLUT.cmake` is not installed on Windows:
Linux:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=969952&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=1964
Windows:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=969952&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc&l=2373
***
=> [build] Fix GLUT dependency handling on Windows

dart/config.hpp.in
=> Fix missing parentheses in config.hpp

dart/dynamics/MeshShape.cpp, dart/dynamics/MeshShape.hpp, python/dartpy/dynamics/Shape.cpp
This PR supports negative scaling in MeshShape as requested #1839. While it's not extensively tested yet, initial results are promising. Scaling the pelvis mesh by positive (5) and negative (-5) values worked as expected in preliminary tests.
Pelvis with scale(5, 5, 5):
https://github.com/user-attachments/assets/9bb243a1-ba4b-479c-944d-cb2de7541b31
Pelvis with scale(-5, -5, -5):
https://github.com/user-attachments/assets/81ada3b6-6f55-40bd-bd35-0dbeb49fd3a8
Resolves #1839.
***
=> Allow negative scale for MeshShape

docs/readthedocs/conf.py
RTD build fixed:
- https://readthedocs.org/projects/dart/builds/26233094/
- https://readthedocs.org/projects/dart-ko/builds/26233093/
***
=> Remove unsupported option "display_version"

dart/gui/osg/ImGuiHandler.cpp, pixi.lock, pixi.toml
- Updated the special key mapping between OSG and ImGui as per https://github.com/ocornut/imgui/issues/4921 to resolve build issues caused by the removed ImGui API since version 1.91.5.
- Renamed the Pixi task from `configure` to `config` for brevity.
***
=> Support ImGui 1.91.5 and greater

cmake/DARTFindOpenSceneGraph.cmake, dart/gui/CMakeLists.txt, dart/gui/osg/CMakeLists.txt
This PR is to prevent the downstream packages need to manually add `find_package(imgui)`, which is not ideal.
The generated `dart_gui-osgComponent.cmake` should contain both `imgui` and `OpenSceneGraph`.
Before:
```cmake
set("dart_gui-osg_DEPENDENCIES" gui)
set("dart_gui-osg_LIBRARIES" dart-gui-osg)
set_property(DIRECTORY PROPERTY "DART_gui-osg_FOUND" TRUE)
foreach(external_dep OpenSceneGraph)
...
endforeach()
```
After:
```cmake
set("dart_gui-osg_DEPENDENCIES" gui)
set("dart_gui-osg_LIBRARIES" dart-gui-osg)
foreach(external_dep OpenSceneGraph;imgui)
...
endforeach()
```
I also changed the error to a warning for building with old OSG (< 3.7.0) on macOS to allow building with the old version but with a patch for the issue.
***
=> Fix imgui is not properly set when DART_USE_SYSTEM_IMGUI=ON

CHANGELOG.md
=> Packaging 6.15.0

CMakeLists.txt, tests/benchmark/CMakeLists.txt
Hi,
This PR allow use of  installed google benchmark instead of downloading it at configure time.
***
=> CMake: add DART_USE_SYSTEM_GOOGLEBENCHMARK

CMakeLists.txt, python/CMakeLists.txt
Hi,
This follows #1904, but for python bindings.
ref. https://pybind11.readthedocs.io/en/stable/compiling.html
***
=> CMake: add DART_USE_SYSTEM_PYBIND11

dart/collision/CollisionGroup.cpp
- fix typo "tehre" -> "there" in `CollisionGroup.cpp`
- `n/a`
=> Fix typo in CollisionGroup comment

.github/workflows/api_doc.yml
- fix apt package list for API docs workflow
- install `clang-format-14` instead of unavailable `clang-format-12`
- `pytest -q` *(fails: command not found)*
=> Fix API doc workflow for Ubuntu 24.04

python/tests/unit/collision/test_collision.py, python/tests/unit/dynamics/test_inverse_kinematics.py, python/tests/unit/dynamics/test_meta_skeleton.py, python/tests/unit/math/test_random.py, python/tests/unit/optimizer/test_optimizer.py, python/tests/unit/simulation/test_world.py
- fix misuse of `is` for numeric equality checks in Python test suite
- `python -m py_compile python/tests/unit/dynamics/test_inverse_kinematics.py`
- `python -m py_compile python/tests/unit/dynamics/test_meta_skeleton.py`
- `python -m py_compile python/tests/unit/optimizer/test_optimizer.py`
- `python -m py_compile python/tests/unit/collision/test_collision.py`
- `python -m py_compile python/tests/unit/simulation/test_world.py`
- `python -m py_compile python/tests/unit/math/test_random.py`
=> Fix identity comparisons in unit tests

pixi.lock, pixi.toml
=> [pixi] Upgrade dependency versions
