dart/dynamics/Skeleton.cpp
dart/dynamics/Skeleton.h

... that returns `getNumBodyNodes()`.

Add Skeleton::getNumJoints() 

---

CMakeLists.txt
ci/before_install.sh
dart/gui/GLFuncs.cpp
dart/gui/GlutWindow.cpp
dart/gui/LoadGlut.h
dart/gui/SimWindow.cpp
dart/gui/SoftSimWindow.cpp
dart/gui/Win2D.cpp
dart/gui/Win3D.cpp
dart/renderer/LoadOpengl.h
debian/control

Move glut dependency from dart-core to dart

---

dart/dynamics/BallJoint.cpp
dart/dynamics/BallJoint.h
dart/dynamics/EulerJoint.cpp
dart/dynamics/EulerJoint.h
dart/dynamics/FreeJoint.cpp
dart/dynamics/FreeJoint.h
dart/dynamics/Joint.h
dart/dynamics/MultiDofJoint.h
dart/dynamics/PlanarJoint.cpp
dart/dynamics/PlanarJoint.h
dart/dynamics/SingleDofJoint.cpp
dart/dynamics/SingleDofJoint.h
dart/dynamics/Skeleton.cpp
dart/dynamics/Skeleton.h
dart/dynamics/TranslationalJoint.cpp
dart/dynamics/TranslationalJoint.h
dart/dynamics/UniversalJoint.cpp
dart/dynamics/UniversalJoint.h
dart/dynamics/ZeroDofJoint.cpp
dart/dynamics/ZeroDofJoint.h
unittests/testDynamics.cpp

This pull request adds the same functionality of #389 to DART 4.3 for the users who want to stay with DART 4.3 but need this feature. 
Targeting DART 4.4 branch instead of DART 4.3 since it's adding new feature.

Differences of generalized coordinates for DART 4.4

---

dart/dynamics/SingleDofJoint.cpp
dart/dynamics/detail/MultiDofJoint.h

Same as #429 but targeted for master branch, because the other one cannot be directly merged into master.

Joint warning improvements

---

dart/utils/sdf/SdfParser.cpp
dart/utils/sdf/SdfParser.h
data/sdf/test/single_bodynode_skeleton.world
unittests/testParser.cpp

Same as #444 but targeted at master.

More robust SDF parser -- master

---

dart/common/Signal.h
dart/common/detail/Signal.h

Revised version of #457 
--
clenaupConnections --> cleanupConnections
Fixes #442, thanks to @mkoval

Fix typo in function name: clenaupConnections --> cleanupConnections

---

ci/before_install_osx.sh

I believe this PR will fix the current travis-ci build failures on mac.

Update homebrew formula before installing pacakges

---

dart/dynamics/Frame.cpp
dart/dynamics/Frame.h

Add Frame::getTransform(withRespecTo, inCoordinatesOf)

---

dart/dynamics/SingleDofJoint.cpp
dart/dynamics/detail/MultiDofJoint.h

This pull request a temporary fix for testJoint test failure for 5.1. Current command handling will be improved in DART 6.0 introducing actuator class.

Fix testJoint test

---

dart/dynamics/Skeleton.cpp
dart/dynamics/Skeleton.h

Fix typo: adjecent --> adjacent

---

dart/dynamics/BodyNode.cpp
dart/dynamics/Joint.cpp

This change was made based on the discussion in #500.

More efficient Jacobian update checking

---

dart/dynamics/BodyNode.cpp
dart/dynamics/BodyNode.h
dart/dynamics/Joint.cpp
unittests/testForwardKinematics.cpp

Same as #500 but targeted for the master branch.

Dirtying Jacobian update flags whenever the parent transform is changed -- master patch

---

dart/optimizer/GradientDescentSolver.cpp
dart/optimizer/Solver.cpp
dart/optimizer/Solver.h
unittests/testOptimizer.cpp

Note that this PR is targeting `grey/osg` branch.

Allow to specify the stream for optimization Solver's output

---

appveyor.yml
dart/dynamics/InverseKinematics.cpp
dart/dynamics/InverseKinematics.h
dart/dynamics/Skeleton.h
dart/utils/urdf/DartLoader.cpp

This PR is a patch for #512 and other similar errors.

Resolve Eigen alignment issues of recent changes (Fix #512)

---

dart/dynamics/BodyNode.h
dart/dynamics/Entity.h
dart/dynamics/Frame.h
dart/dynamics/Joint.h
dart/dynamics/MetaSkeleton.h
dart/dynamics/Skeleton.h

Same as #525 but targeted for release-5.1

Fix Copy Safety -- Patch for 5.1

---

ci/before_install_linux.sh

Travis build test with Bullet

---

dart/dynamics/detail/MultiDofJointProperties.h
unittests/testAddon.cpp
unittests/testOptimizer.cpp

Make a default argument for MultiDofJointAddon

---

.travis.yml

This PR resolved #687 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/688)

Remove coveralls token from .travis.yml

---

dart/collision/CollisionGroup.hpp
dart/collision/detail/CollisionGroup.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/704)

Switch CollisionGroup to take MetaSkeleton instead of Skeleton

---

dart/common/detail/Composite.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/707)

Fix typo in utility macro for specialized aspect: erase --> remove

---

debian/libdart6-dev.install

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/709)

Update debian script to install .hpp instead of .h

---

unittests/testCollision.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/719)

Fix Eigen memory alignment issue in testCollision.cpp

---

dart/dynamics/Skeleton.cpp
dart/dynamics/Skeleton.hpp
tutorials/tutorialBiped-Finished.cpp
unittests/TestHelpers.hpp
unittests/testJoints.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/718)

Separate enableSelfCollision into two concrete functions

---

dart/dynamics/Skeleton.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/727)

Minor comment typo correction

---

CHANGELOG.md
dart/collision/fcl/FCLCollisionDetector.cpp
dart/collision/fcl/FCLCollisionDetector.hpp
dart/collision/fcl/FCLCollisionObject.cpp
dart/collision/fcl/FCLCollisionObject.hpp
dart/collision/fcl/FCLTypes.hpp
dart/utils/XmlHelpers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/750)

Update API to support fcl 0.5 and tinyxml 4.0 -- for DART 6.1

---

CHANGELOG.md
dart/gui/GlutWindow.cpp
dart/math/Helpers.hpp
dart/utils/CompositeResourceRetriever.cpp
dart/utils/VskParser.cpp
tutorials/tutorialCollisions-Finished.cpp
tutorials/tutorialCollisions.cpp

The Debian QA checker detected some spelling errors while submitting the package to Debian.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/756)

Fix spelling errors detected by Debian QA checker

---

Changelog.md
dart/collision/fcl/FCLCollisionNode.cpp
dart/collision/fcl/FCLTypes.h
dart/utils/Parser.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/759)

Backport #749 to DART 5.1

---

CHANGELOG.md
cmake/DARTFindDependencies.cmake
cmake/FindFLANN.cmake
dart/config.hpp.in
unittests/CMakeLists.txt
unittests/testNearestNeighbor.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/761)

Link to flann properly

---

CHANGELOG.md
dart/collision/bullet/BulletCollisionDetector.cpp
data/skel/shapes.skel
unittests/testCollision.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/763)

Fix direction of contact normal of BulletCollisionDetector

---

CHANGELOG.md
debian/changelog
debian/control
debian/libdart6-utils-dev.install
debian/libdart6-utils-urdf-dev.install
debian/libdart6-utils-urdf.install

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/782)

Packaging 6.0.1

---

CHANGELOG.md
dart/utils/sdf/SdfParser.cpp
debian/changelog
unittests/testSkelParser.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/783)

5.1 --> master

---

CHANGELOG.md
debian/changelog
debian/libdart6-utils-urdf-dev.install

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/784)

Packaging 6.1.0

---

Changelog.md
debian/changelog
package.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/785)

Packaging 5.1.3

---

CHANGELOG.md
dart/external/lodepng/lodepng.cpp
dart/external/lodepng/lodepng.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/791)

Update LodePNG up to version 20160501

---

CMakeLists.txt
Changelog.md
apps/addDeleteSkels/MyWindow.cpp
apps/atlasSimbicon/MyWindow.cpp
apps/bipedStand/MyWindow.cpp
apps/hybridDynamics/MyWindow.cpp
apps/jointConstraints/MyWindow.cpp
apps/mixedChain/MyWindow.cpp
apps/rigidCubes/MyWindow.cpp
apps/rigidShapes/MyWindow.cpp
apps/softBodies/MyWindow.cpp
apps/vehicle/MyWindow.cpp
dart/gui/GlutWindow.cpp
dart/gui/GlutWindow.h
dart/gui/SimWindow.cpp
dart/gui/SoftSimWindow.cpp
debian/changelog
package.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/796)

Packaging 5.1.4

---

CHANGELOG.md
dart/gui/GlutWindow.cpp
dart/gui/GlutWindow.hpp
dart/gui/SimWindow.cpp
dart/gui/SoftSimWindow.cpp
examples/addDeleteSkels/MyWindow.cpp
examples/atlasSimbicon/MyWindow.cpp
examples/bipedStand/MyWindow.cpp
examples/hybridDynamics/MyWindow.cpp
examples/jointConstraints/MyWindow.cpp
examples/mixedChain/MyWindow.cpp
examples/rigidCubes/MyWindow.cpp
examples/rigidShapes/MyWindow.cpp
examples/softBodies/MyWindow.cpp
examples/vehicle/MyWindow.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/795)

Fix inconsistent frame rate of GlutWindow -- DART 6.1.1

---

CHANGELOG.md
debian/changelog
debian/control
debian/copyright
debian/libdart6-collision-bullet-dev.install
debian/libdart6-dev.install
debian/libdart6-external-imgui-dev.install
debian/libdart6-external-lodepng-dev.install
debian/libdart6-external-odelcpsolver-dev.install
debian/libdart6-gui-dev.install
debian/libdart6-gui-osg-dev.install
debian/libdart6-optimizer-ipopt-dev.install
debian/libdart6-optimizer-nlopt-dev.install
debian/libdart6-planning-dev.install
debian/libdart6-utils-dev.install
debian/libdart6-utils-urdf-dev.install

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/797)

Packaging 6.1.1

---

CMakeLists.txt
Changelog.md
dart/collision/fcl/FCLTypes.h
dart/common/Deprecated.h
dart/config.h.in
dart/utils/urdf/DartLoader.cpp
dart/utils/urdf/URDFTypes.h
dart/utils/urdf/urdf_world_parser.h
package.xml
unittests/testOptimizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/800)

Increase minimum required Ipopt version to 3.11.9

---

dart/optimizer/ipopt/IpoptSolver.cpp
dart/optimizer/nlopt/NloptSolver.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/801)

Remove unnecessary static_cast in optimizers

---

CHANGELOG.md
dart/dynamics/BodyNode.cpp
unittests/comprehensive/test_Skeleton.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/818)

Fix that ZeroDofJoint::getIndexInTree() is called

---

examples/addDeleteSkels/MyWindow.cpp

Related issue: #824
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/825)

[addDeleteSkel] Set inertia according to size and mass

---

CHANGELOG.md
dart/dynamics/Skeleton.cpp
dart/dynamics/Skeleton.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/832)

Add Skeleton::getRootJoint()

---

CHANGELOG.md
debian/changelog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/835)

Packaging 6.1.2

---

Changelog.md
debian/changelog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/836)

Packaging 5.1.5

---

dart/utils/sdf/SdfParser.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/849)

The same bug for SDF Parser

---

dart/math/ConfigurationSpace.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dartsim/dart/852)

Use static constexpr instead of enum class

---

.travis.yml
README.md
ci/script.sh
dart/collision/CollisionFilter.cpp
dart/utils/SkelParser.cpp
dart/utils/sdf/SdfParser.cpp
dart/utils/urdf/DartLoader.cpp
unittests/regression/CMakeLists.txt
unittests/regression/test_Issue895.cpp
unittests/unit/test_DartLoader.cpp

There were some PRs for 6.2.1 those were merged to master instead of release-6.1. This PR merges master into release-6.2 to resolve that. Once this PR is merged, master will bump the version to 6.3.0, and all the future PRs for 6.2.1 should target release-6.2.

Merge master into release-6.2

---

.travis.yml

Cache apt and Homebrew to speed up Travis CI

---

CHANGELOG.md

release-5.1 --> release-6.4

---

paper/paper.bib

This PR adds DOIs to the bibtex entries for the [JOSS submission](https://github.com/openjournals/joss-reviews/issues/500).
Resolves #949

Add DOI to bibtex entries

---

CMakeLists.txt
Changelog.md
cmake/FindFLANN.cmake
dart/config.h.in
dart/utils/Parser.cpp
dart/utils/urdf/BackwardCompatibility.h
dart/utils/urdf/DartLoader.cpp
unittests/CMakeLists.txt
unittests/testNearestNeighbor.cpp

Update DART 4.3 to be compatible with the latest macOS

---

CHANGELOG.md

Update changelog for #964

---

README.md

[Codacy](https://app.codacy.com) is an automated code reviews and code analytics service. [Here](https://app.codacy.com/app/jslee02/dart/dashboard) is the dashboard for DART.
Codacy has several static analysis tools where two of them (cppcheck and shellcheck) are applicable to DART.
I found two other alternatives to Codacy, but they don't fit DART because:
* [Codebeat](https://codebeat.co/) doesn't support C++ projects
* [Code Climate](https://codeclimate.com/) isn't free for open source projects

Setup online static code analyzer: Codacy

---

CMakeLists.txt
doxygen/Doxyfile.in

This PR ports https://github.com/personalrobotics/aikido/pull/319 into DART thanks to @brianhou.
***

Cleanup doxygen

---

.github/stale.yml

See https://github.com/probot/stale for more details.

Add probot-stale configuration

---

.clang-format
dart/lcpsolver/Lemke.cpp
dart/lcpsolver/ODELCPSolver.cpp

Once this PR is merged, we will apply this to the existing code and enforce style check using Travis CI.

Update clang-format configurations

---

ci/script.sh

Add installation test to Travis

---

.appveyor.yml
cmake/DARTFindDependencies.cmake

based on https://github.com/dartsim/dart/issues/1001

Update boost dependencies on Windows

---

dart/dynamics/GenericJoint.hpp
dart/dynamics/Joint.hpp
dart/dynamics/ZeroDofJoint.cpp
dart/dynamics/ZeroDofJoint.hpp
dart/dynamics/detail/GenericJoint.hpp

Add const qualifier to Joint::getForce()

---

examples/osgExamples/osgAtlasPuppet/osgAtlasPuppet.cpp

Fix Eigen aliasing issue

---

dart/collision/CollisionGroup.hpp
dart/collision/detail/CollisionGroup.hpp

This PR is a sequel to #704.
***

Change CollisionGroup::removeShapeFramesOf() to take MetaSkeleton

---

dart/common/Mutex.cpp
dart/common/Mutex.hpp
dart/dynamics/MetaSkeleton.cpp
dart/dynamics/MetaSkeleton.hpp
dart/dynamics/ReferentialSkeleton.cpp
dart/dynamics/ReferentialSkeleton.hpp
dart/dynamics/Skeleton.cpp
dart/dynamics/Skeleton.hpp
unittests/comprehensive/test_Skeleton.cpp

This PR is a prototype of mutex(es) wrapper class based on @psigen's [comment](https://github.com/dartsim/dart/pull/1011#pullrequestreview-99150832) in #1011.

Add Mutex class

---

.appveyor.yml

This PR fixes the recent build failures of AppVeyor tests.

Update vcpkg before installing packages

---

ci/install_osx.sh

so that we can speed up CI tests on macOS
***

Install ode and bullet w/o options

---

docs/readthedocs/tutorials/dominoes.md
unittests/comprehensive/test_Joints.cpp
unittests/regression/test_Issue986.cpp

Replace utils with io

---

.appveyor.yml

It's a good news AppVeyor supports Ubuntu 16.04 (in beta)!
**TODO**

Add build testing on Ubuntu 16.04 to AppVeyor

---

CHANGELOG.md
dart/common/Memory.hpp

This PR partially resolves #1035.
***

Fix build with Eigen 3.2.1-3.2.8

---

CHANGELOG.md
dart/common/Memory.hpp

Add missing <vector> to Memory.hpp

---

dart/dynamics/BodyNode.cpp
dart/dynamics/BodyNode.hpp

Add warning for invalid mass

---

examples/osgExamples/osgWamIkFast/CMakeLists.txt
examples/osgExamples/osgWamIkFast/Helpers.cpp
examples/osgExamples/osgWamIkFast/InSourceBuild.cmake
examples/osgExamples/osgWamIkFast/ikfast/CMakeLists.txt
examples/osgExamples/osgWamIkFast/ikfast/InSourceBuild.cmake

Fix osgWamIkFast build

---

CHANGELOG.md
CMakeLists.txt
examples/humanJointLimits/CMakeLists.txt
examples/rigidCubes/CMakeLists.txt
package.xml

This PR partially fixes #1091.

Fix example build 6.6

---

dart/math/Random.cpp
dart/math/Random.hpp
dart/math/detail/Random-impl.hpp

as suggested: https://github.com/dartsim/dart/pull/1109#discussion_r216658502

Remove redundant function name

---

CHANGELOG.md
dart/external/imgui/CMakeLists.txt
dart/gui/osg/DefaultEventHandler.cpp

Fix compilation issues on Ubuntu 18.04 [release-6.7]

---

dart/external/imgui/imconfig.h
dart/external/imgui/imgui.cpp
dart/external/imgui/imgui.h
dart/external/imgui/imgui_draw.cpp
dart/external/imgui/imgui_internal.h
dart/external/imgui/imgui_widgets.cpp
dart/external/imgui/imstb_rectpack.h
dart/external/imgui/imstb_textedit.h
dart/external/imgui/imstb_truetype.h

Update to imgui 1.65

---

CMakeLists.txt
examples/humanJointLimits/InSourceBuild.cmake

They will appear with DART_VERBOSE option.
***

Cleanup detailed cmake output

---

.azure-pipelines.yml
.ci/docker/Dockerfile.ubuntu-xenial-32bit
unittests/unit/test_ContactConstraint.cpp

Fix failure of ContactConstraint.ContactWithKinematicJoint on Ubuntu 32-bit

---

CHANGELOG.md
dart/collision/CollisionFilter.cpp
unittests/regression/CMakeLists.txt
unittests/regression/test_Issue1231.cpp

Ignore collisions between non-mobile bodies

---

dart/dynamics/Group.cpp

Add missing definition of Group::removeJoints(...)

---

CHANGELOG.md
cmake/Findassimp.cmake
cmake/Findccd.cmake
cmake/Findfcl.cmake
cmake/Findflann.cmake
cmake/Findtinyxml2.cmake

Fix not failing for missing required dependencies

---

CHANGELOG.md
dart/CMakeLists.txt

Fix linking to octomap when not imported

---

CHANGELOG.md
dart/gui/osg/GridVisual.cpp
examples/osgExamples/osgPointCloud/main.cpp

Fix missing definition of GridVisual::isDisplayed()

---

CHANGELOG.md
dart/utils/VskParser.cpp
unittests/unit/CMakeLists.txt
unittests/unit/test_VskParser.cpp

Thanks @sehoonha for reporting this bug.
***

Fix VskParser returning incorrect resource retriever

---

CHANGELOG.md
cmake/DARTFindIPOPT.cmake
cmake/DARTFindpagmo.cmake
dart/optimizer/ipopt/IpoptSolver.hpp
dart/optimizer/pagmo/CMakeLists.txt
dart/optimizer/pagmo/PagmoMultiObjectiveSolver.cpp
dart/optimizer/pagmo/PagmoMultiObjectiveSolver.hpp

Fix building with pagmo's optional dependencies

---

dart/common/LockableReference.hpp
dart/constraint/BallJointConstraint.hpp
dart/constraint/BoxedLcpConstraintSolver.hpp
dart/dynamics/BodyNode.hpp
dart/dynamics/CapsuleShape.hpp
dart/dynamics/FreeJoint.hpp
dart/dynamics/InverseKinematics.hpp
dart/dynamics/Joint.hpp
dart/dynamics/PlanarJoint.hpp
dart/dynamics/PointCloudShape.hpp
dart/dynamics/PointMass.hpp
dart/dynamics/Skeleton.hpp
dart/dynamics/SoftBodyNode.hpp
dart/gui/osg/RealTimeWorldNode.hpp
dart/math/Geometry.hpp
dart/simulation/World.hpp

Starting progress on fixing Doxygen warnings #275.
No new code, just typos and documentation fixes.

Doxygen Warning Fixes

---

CHANGELOG.md
python/dartpy/gui/osg/GridVisual.cpp
python/dartpy/gui/osg/Viewer.cpp
python/examples/hello_world_gui/main.py

[dartpy] Add grid visual

---

CHANGELOG.md
python/dartpy/dynamics/Chain.cpp
python/dartpy/dynamics/Joint.cpp
python/dartpy/dynamics/Linkage.cpp
python/dartpy/dynamics/ReferentialSkeleton.cpp
python/dartpy/dynamics/Skeleton.cpp
python/dartpy/dynamics/module.cpp
python/tests/CMakeLists.txt
python/tests/unit/dynamics/test_meta_skeleton.py

[dartpy] Add ReferentialSkeleton, Linkage, and Chain

---

CHANGELOG.md
dart/gui/osg/RealTimeWorldNode.hpp
dart/gui/osg/WorldNode.hpp
data/urdf/KR5/ground.urdf
python/dartpy/dynamics/Chain.cpp
python/dartpy/dynamics/Skeleton.cpp
python/dartpy/gui/osg/GridVisual.cpp
python/dartpy/gui/osg/RealTimeWorldNode.cpp
python/dartpy/gui/osg/Viewer.cpp
python/dartpy/gui/osg/ViewerAttachment.cpp
python/dartpy/gui/osg/WorldNode.cpp
python/examples/hello_world_gui/main.py

[dartpy] Allow WorldNode classes to overload virtual functions

---

CHANGELOG.md
python/dartpy/common/Observer.cpp
python/dartpy/dynamics/Shape.cpp
python/dartpy/dynamics/ShapeFrame.cpp
python/dartpy/dynamics/module.cpp
python/dartpy/gui/osg/DragAndDrop.cpp
python/dartpy/gui/osg/Viewer.cpp
python/dartpy/gui/osg/module.cpp
python/examples/operational_space_control/main.py
python/tests/unit/dynamics/test_aspect.py

[dartpy] Add shapes and ShapeFrame aspects

---

CHANGELOG.md
dart/gui/osg/render/PointCloudShapeNode.cpp
examples/point_cloud/main.cpp

Fix incorrect PointCloudShape transparency

---

CHANGELOG.md
python/dartpy/dynamics/BodyNode.cpp
python/dartpy/dynamics/EulerJoint.cpp
python/dartpy/dynamics/Joint.cpp
python/dartpy/dynamics/Joint.hpp
python/dartpy/dynamics/PlanarJoint.cpp
python/dartpy/dynamics/PrismaticJoint.cpp
python/dartpy/dynamics/ScrewJoint.cpp
python/dartpy/dynamics/Skeleton.cpp
python/dartpy/dynamics/TranslationalJoint.cpp
python/dartpy/dynamics/TranslationalJoint2D.cpp
python/dartpy/dynamics/UniversalJoint.cpp
python/dartpy/dynamics/WeldJoint.cpp
python/dartpy/dynamics/ZeroDofJoint.cpp
python/dartpy/dynamics/module.cpp
python/dartpy/math/Geometry.cpp
python/dartpy/math/module.cpp
python/tests/CMakeLists.txt
python/tests/unit/dynamics/test_joint.py
unittests/comprehensive/test_Joints.cpp

[dartpy] Add all the joint types

---

README.md

added deprecation notice next to pydart2

---

CHANGELOG.md
dart/gui/osg/render/PointCloudShapeNode.cpp

Set data variance of PointCloudShapeNode to DYNAMIC

---

CHANGELOG.md
python/dartpy/dynamics/InverseKinematics.cpp
python/dartpy/gui/osg/RealTimeWorldNode.cpp
python/dartpy/gui/osg/ShadowTechnique.cpp
python/dartpy/optimizer/Solver.cpp
python/dartpy/simulation/World.cpp
python/tests/unit/dynamics/test_inverse_kinematics.py

[dartpy] Add findSolution and solveAndApply to InverseKinematics

---

CMakeLists.txt

This is motivated by [this comment](https://github.com/flexible-collision-library/fcl/pull/409#issuecomment-506639644).

Extract version number from package.xml

---

.appveyor.yml
.azure-pipelines.yml
.ci/install_linux.sh
.github/workflows/ccpp.yml
.travis.yml

Build distributions:
|                       | GitHub Actions | Travis CI | Azure Pipelines | Appveyor |
|-----------------------|----------------|-----------|-----------------|----------|
| Maximum Parallel Jobs | 20             | 5         | 10              | 1
| Assigned Jobs         | 10             | 3         | 6               | 1 (only CMake)

Split build tests to balance loads on CI services

---

CHANGELOG.md
cmake/Findfcl.cmake

***
- [N/A] Document new methods and classes
- [N/A] Format new code files using `clang-format`
- [N/A] Add unit test(s) for this change

Update Findfcl.cmake to support FCL 0.6

---

dart/collision/CollisionResult.cpp

Add newline at the end of error message

---

.ci/install_linux.sh
.ci/install_osx.sh
.ci/script.sh
Brewfile
unittests/comprehensive/test_MultiObjectiveOptimization.cpp

Build DART with pagmo2 in CI

---

CHANGELOG.md
dart/external/imgui/imconfig.h
dart/external/imgui/imgui.cpp
dart/external/imgui/imgui.h
dart/external/imgui/imgui_draw.cpp
dart/external/imgui/imgui_impl_opengl2.cpp
dart/external/imgui/imgui_impl_opengl2.h
dart/external/imgui/imgui_internal.h
dart/external/imgui/imgui_widgets.cpp
dart/external/imgui/imstb_rectpack.h
dart/external/imgui/imstb_textedit.h
dart/external/imgui/imstb_truetype.h

Update Dear ImGui to 1.79

---

.azure-pipelines.yml
.github/workflows/ccpp.yml

- Format YAML configuration files using VSCode
- Build DART and dartpy together

Cleanup CI settings

---

examples/deprecated_examples/glut_human_joint_limits/CMakeLists.txt
python/dartpy/collision/CollisionFilter.cpp
python/dartpy/collision/CollisionGroup.cpp
python/dartpy/collision/module.cpp
python/dartpy/dynamics/Node.cpp
python/dartpy/dynamics/ShapeNode.cpp

Add more Python bindings for collision and dynamics

---

python/dartpy/dynamics/InverseKinematics.cpp

Add missing Python bindings for TSR

---

CHANGELOG.md
dart/gui/OpenGLRenderInterface.cpp

Set back face culling by default

---

dart/dynamics/CapsuleShape.cpp

Fix inertia calculation of CapsuleShape

---

CHANGELOG.md
dart/external/imgui/imconfig.h
dart/external/imgui/imgui.cpp
dart/external/imgui/imgui.h
dart/external/imgui/imgui_draw.cpp
dart/external/imgui/imgui_impl_opengl2.cpp
dart/external/imgui/imgui_impl_opengl2.h
dart/external/imgui/imgui_internal.h
dart/external/imgui/imgui_tables.cpp
dart/external/imgui/imgui_widgets.cpp
dart/external/imgui/imstb_textedit.h
dart/external/imgui/imstb_truetype.h
extras/dartc/src/SkeletonManager.hpp

Upgrade ImGui to 1.82

---

CHANGELOG.md
cmake/DARTFindfcl.cmake
dart/collision/fcl/BackwardCompatibility.hpp
dart/collision/fcl/FCLCollisionDetector.cpp
dart/collision/fcl/FCLCollisionDetector.hpp
dart/collision/fcl/FCLCollisionObject.cpp
dart/collision/fcl/FCLCollisionObject.hpp
dart/dynamics/VoxelGridShape.cpp
dart/dynamics/VoxelGridShape.hpp
extras/dartc/src/SkeletonManager.hpp

as the default FCL version of Ubuntu 18.04 is 0.5.0
***

Drop supporting FCL < 0.5.0

---

dart/CMakeLists.txt
dart/external/lodepng/CMakeLists.txt
dart/external/odelcpsolver/CMakeLists.txt
dart/gui/CMakeLists.txt
dart/gui/glut/CMakeLists.txt

Make external-odelcpsolver and external-lodepng as private dependencies

---

dart/dynamics/MetaSkeleton.cpp

Fix incorrect index checking in getValuesFromVector() in MetaSkeleton.cpp

---

CMakeLists.txt
cmake/DARTFindDependencies.cmake
cmake/DARTFindspdlog.cmake
cmake/DARTMacros.cmake
dart/collision/detail/engine_impl.hpp
dart/collision/engine.hpp
dart/common/CMakeLists.txt
dart/common/detail/Aspect.hpp
dart/common/detail/logging_impl.hpp
dart/common/logging.cpp
dart/common/logging.hpp
dart/common/macro.hpp
dart/math/ODELCPSolver.cpp
dart/optimization/ipopt/IpoptSolver.cpp
tests/unit/collision/test_narrow_phase_interface.cpp
tests/unit/common/test_logging.cpp
tools/run

Integrate spdlog with basic functionalities

---

CMakeLists.txt
cmake/dart.pc.in

Updated dart.pc.in based on the suggestions in #1496 and https://people.freedesktop.org/~dbn/pkg-config-guide.html

Fix dart.pc (#1496)

---

CHANGELOG.md
dart/external/imgui/imconfig.h
dart/external/imgui/imgui.cpp
dart/external/imgui/imgui.h
dart/external/imgui/imgui_draw.cpp
dart/external/imgui/imgui_impl_opengl2.cpp
dart/external/imgui/imgui_impl_opengl2.h
dart/external/imgui/imgui_internal.h
dart/external/imgui/imgui_tables.cpp
dart/external/imgui/imgui_widgets.cpp
dart/external/imgui/imstb_rectpack.h
dart/external/imgui/imstb_textedit.h
dart/external/imgui/imstb_truetype.h

Updata ImGui to 1.84.2

---

CHANGELOG.md
python/dartpy/common/Resource.cpp
python/dartpy/common/ResourceRetriever.cpp
python/dartpy/utils/MjcfParser.cpp
python/dartpy/utils/ResourceRetriever.cpp
python/dartpy/utils/SdfParser.cpp
python/dartpy/utils/SkelParser.cpp
python/dartpy/utils/module.cpp
python/tests/unit/utils/test_sdf_parser.py
python/tests/unit/utils/test_skel_parser.py

in response to https://dartsim.discourse.group/t/to-parse-sdf-in-dartpy/261
***

Add Python bindings for ResourceRetriever and SdfParser

---

CHANGELOG.md
CONTRIBUTING.md

@azeey @costashatz Feel free to update the change log and the contribution descriptions. Thank you for your contributions again!

Update changelog and contribution for #1620 and #1624

---

CHANGELOG.md
CONTRIBUTING.md

Update changelog and contribution for #1624

---

dart/simulation/World.cpp
dart/simulation/World.hpp
examples/deprecated_examples/glut_biped_stand/Main.cpp
python/dartpy/simulation/World.cpp

Add World::setGravity(double x, double y, double z)

---

CHANGELOG.md
cmake/DARTFindBoost.cmake
cmake/DARTFindassimp.cmake
cmake/DARTFindoctomap.cmake
dart/collision/fcl/BackwardCompatibility.hpp
dart/collision/fcl/FCLCollisionDetector.cpp
dart/collision/fcl/FCLCollisionDetector.hpp
dart/collision/fcl/FCLCollisionObject.cpp
dart/collision/fcl/FCLCollisionObject.hpp
dart/constraint/ConstraintSolver.cpp
dart/constraint/ContactSurface.hpp
dart/dynamics/VoxelGridShape.cpp
dart/dynamics/VoxelGridShape.hpp
unittests/integration/test_ConstraintSolver.cpp

Drop supporting FCL < 0.5

---

.github/workflows/ci_macos.yml
CHANGELOG.md
dart/dynamics/BodyNode.cpp

Fix setResitutionCoeff() calling setFrictionCoeff()

---

python/examples/hello_world/main.py

to fix https://github.com/dartsim/dart/actions/runs/3642797962/jobs/6150318390#step:4:2564
***

Use == instead of 'is' to compare integer

---

.ci/build.sh
.github/workflows/ci_macos.yml
python/examples/CMakeLists.txt

This fixes the CI issue for Windows.

cmake pythonpath fix

---

.github/workflows/ci_macos.yml

as it takes too long: https://github.com/dartsim/dart/actions/runs/3723323990/jobs/6324885433

Remove upterm from macOS CI

---

CMakeLists.txt
dart/CMakeLists.txt

Enable multi-threaded compilation for all the code (MSVC)

---

CHANGELOG.md

Packaging 6.13

---

CHANGELOG.md
dart/constraint/BalanceConstraint.cpp
dart/constraint/BalanceConstraint.hpp
dart/dynamics/HierarchicalIK.cpp
dart/dynamics/HierarchicalIK.hpp
dart/dynamics/InverseKinematics.cpp
dart/dynamics/InverseKinematics.hpp
dart/optimizer/Function.cpp
dart/optimizer/Function.hpp
examples/atlas_puppet/main.cpp
examples/hubo_puppet/main.cpp
python/dartpy/optimizer/Function.cpp
unittests/integration/test_Optimizer.cpp

Rework of https://github.com/dartsim/dart/pull/928
***

Make Function::eval() const [4/N]

---

CHANGELOG.md
dart/CMakeLists.txt
dart/external/lodepng/CMakeLists.txt
dart/external/odelcpsolver/CMakeLists.txt
dart/gui/CMakeLists.txt
dart/gui/glut/CMakeLists.txt

Rework of https://github.com/dartsim/dart/pull/1574
***

Make odelcpsolver and lodepng private targets

---

dart/dynamics/BodyNode.cpp
dart/dynamics/BodyNode.hpp
dart/dynamics/BoxShape.cpp
dart/dynamics/CapsuleShape.cpp
dart/dynamics/ConeShape.cpp
dart/dynamics/CylinderShape.cpp
dart/dynamics/EllipsoidShape.cpp
dart/dynamics/Joint.cpp
dart/dynamics/Joint.hpp
dart/dynamics/LineSegmentShape.cpp
dart/dynamics/MeshShape.cpp
dart/dynamics/MetaSkeleton.cpp
dart/dynamics/MetaSkeleton.hpp
dart/dynamics/MultiSphereConvexHullShape.cpp
dart/dynamics/PlaneShape.cpp
dart/dynamics/PyramidShape.cpp
dart/dynamics/Shape.cpp
dart/dynamics/Shape.hpp
dart/dynamics/SoftMeshShape.cpp
dart/dynamics/SphereShape.cpp
dart/dynamics/detail/HeightmapShape-impl.hpp

Remove deprecated code in 6.1

---

.clang-format
cmake/DARTMacros.cmake
tests/integration/test_MultiObjectiveOptimization.cpp

Put config.hpp above any other dart headers

---

dart/common/SmartPointer.hpp
dart/dynamics/CollisionFilter.cpp
dart/dynamics/CollisionFilter.hpp
examples/deprecated_examples/glut_human_joint_limits/HumanArmJointLimitConstraint.hpp
examples/deprecated_examples/glut_human_joint_limits/HumanLegJointLimitConstraint.hpp

Remove deprecated code in 6.3 and 6.4

---

dart/dynamics/BoxedLcpConstraintSolver.cpp
dart/dynamics/BoxedLcpConstraintSolver.hpp
dart/dynamics/Branch.cpp
dart/dynamics/Branch.hpp
dart/dynamics/Chain.cpp
dart/dynamics/Chain.hpp
dart/dynamics/ConstraintSolver.cpp
dart/dynamics/ConstraintSolver.hpp
dart/dynamics/Group.cpp
dart/dynamics/Group.hpp
dart/dynamics/HierarchicalIK.cpp
dart/dynamics/HierarchicalIK.hpp
dart/dynamics/InverseKinematics.cpp
dart/dynamics/InverseKinematics.hpp
dart/dynamics/Linkage.cpp
dart/dynamics/Linkage.hpp
dart/dynamics/MetaSkeleton.cpp
dart/dynamics/MetaSkeleton.hpp
dart/dynamics/Skeleton.cpp
dart/dynamics/Skeleton.hpp
dart/math/Helpers.hpp
python/dartpy/dynamics/BoxedLcpConstraintSolver.cpp
python/dartpy/dynamics/Chain.cpp
python/dartpy/dynamics/Linkage.cpp
python/dartpy/dynamics/MetaSkeleton.cpp

Remove deprecated code in 6.7 and 6.8

---

dart/dynamics/FreeJoint.cpp
dart/dynamics/FreeJoint.hpp
dart/dynamics/InverseKinematics.cpp
dart/optimization/nlopt/NloptSolver.cpp
dart/optimization/nlopt/NloptSolver.hpp
python/dartpy/optimization/NloptSolver.cpp

Remove deprecated code in 6.9

---

dart/io/CMakeLists.txt
dart/io/CompositeResourceRetriever.hpp
dart/io/DartResourceRetriever.hpp
dart/io/FileInfoC3D.hpp
dart/io/FileInfoDof.hpp
dart/io/FileInfoWorld.hpp
dart/io/PackageResourceRetriever.hpp
dart/io/SkelParser.hpp
dart/io/VskParser.hpp
dart/io/mjcf/MjcfParser.hpp
dart/io/sdf/SdfParser.hpp
dart/io/urdf/DartLoader.hpp
dart/simulation/CMakeLists.txt
dart/simulation/Recording.hpp
dart/simulation/World.hpp

Add symbol control to dart::simulation and dart::io

---

CMakeLists.txt
dart/common/CMakeLists.txt
dart/common/Profile.hpp
tests/unit/common/test_Profile.cpp
tools/CMakeLists.txt
tools/profile/CMakeLists.txt

Set up profiling with Remotery backend support

---

.github/workflows/codeql.yml
dart/io/FileInfoDof.cpp
dart/io/FileInfoWorld.cpp
dart/math/lcp/ODELCPSolver.cpp
tests/unit/math/test_Lcp.cpp

Partially resolve CodeQL issues and set paths to ignore

---

dart/common/Stopwatch.hpp
dart/dynamics/InverseKinematics.hpp
dart/utils/DartResourceRetriever.cpp

- fix comment typo in InverseKinematics.hpp
- fix comment typo in Stopwatch.hpp
- fix comment typo in DartResourceRetriever.cpp
- `git status --short`

Fix comment typos

---

dart/collision/CollisionDetector.hpp
dart/collision/CollisionFilter.hpp
dart/collision/DistanceFilter.hpp
dart/common/Aspect.hpp
dart/common/detail/Aspect.hpp
dart/common/detail/CompositeData.hpp
dart/common/detail/CompositeJoiner.hpp
dart/common/detail/EmbeddedAspect.hpp
dart/constraint/BoxedLcpConstraintSolver.cpp
dart/constraint/ContactConstraint.cpp
dart/dynamics/ArrowShape.cpp
dart/dynamics/CompositeNode.hpp
dart/dynamics/GenericJoint.hpp
dart/dynamics/HierarchicalIK.hpp
dart/dynamics/InverseKinematics.hpp
dart/dynamics/JacobianNode.hpp
dart/dynamics/Joint.hpp
dart/dynamics/MetaSkeleton.hpp
dart/dynamics/detail/EntityNodeAspect.hpp
dart/dynamics/detail/NodeManagerJoiner.hpp
dart/gui/glut/GlutWindow.cpp
dart/gui/osg/InteractiveFrame.cpp
dart/optimizer/MultiObjectiveProblem.hpp
pixi.lock
pixi.toml
tests/integration/test_Collision.cpp

Format code with clang-format-14
